// Textos bilingües de Topos a Mazazos.

export const COPY = {
  es: {
    title: "Topos a Mazazos",
    subtitle: "Whack-a-mole en el jardín: corre, colócate y da mazazos.",
    difficulty: "Dificultad",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    easyDesc: "Rivales lentos: ideal para empezar.",
    mediumDesc: "Rivales avispados y rápidos.",
    hardDesc: "Rivales veloces y certeros.",
    start: "¡A jugar!",
    again: "Otra vez",
    whack: "Golpear",
    pause: "Pausa",
    resume: "Reanudar",
    restart: "Reiniciar",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido",
    soundOff: "Silencio",
    soundLabel: "Activar o desactivar el sonido",
    you: "Tú",
    cpu: "CPU",
    time: "Tiempo",
    best: "Récord",
    youWin: "¡Has ganado!",
    youLose: "Te han superado",
    ready: "¿Preparado?",
    hint:
      "Muévete con las flechas/WASD o el joystick y colócate junto a un agujero; pulsa Golpear (Espacio) para dar un mazazo de área. Topo marrón = 1 punto, dorado = 3. ¡Cuidado con el topo bomba: te resta y te aturde! Rodea los barriles. Gana quien más puntúe en 30 s. P pausa, R reinicia, M sonido y el botón de pantalla completa.",
    paused: "Pausa",
  },
  en: {
    title: "Mallet Moles",
    subtitle: "Garden whack-a-mole: run, line up and swing.",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    easyDesc: "Slow rivals: great to start.",
    mediumDesc: "Sharp, quick rivals.",
    hardDesc: "Fast, accurate rivals.",
    start: "Play!",
    again: "Again",
    whack: "Whack",
    pause: "Pause",
    resume: "Resume",
    restart: "Restart",
    fullscreen: "Fullscreen",
    soundOn: "Sound",
    soundOff: "Muted",
    soundLabel: "Turn the sound on or off",
    you: "You",
    cpu: "CPU",
    time: "Time",
    best: "Best",
    youWin: "You win!",
    youLose: "You were beaten",
    ready: "Ready?",
    hint:
      "Move with the arrows/WASD or the joystick and line up next to a hole; press Whack (Space) for an area swing. Brown mole = 1 point, gold = 3. Watch the bomb mole: it costs points and stuns you! Weave around the barrels. Most points in 30s wins. P pauses, R restarts, M sound, and the fullscreen button.",
    paused: "Paused",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}
