// Bilingual UI copy for Paso a Paso (Step by Step).

export const COPY = {
  es: {
    title: "Paso a paso",
    subtitle: "Elige 1, 3 o 5. Si nadie más saca tu número, subes esos escalones.",
    start: "Comenzar",
    again: "Otra vez",
    restart: "Reiniciar",
    changeSetup: "Cambiar dificultad",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido ON",
    soundOff: "Sonido OFF",
    soundEnable: "Activar sonido",
    soundDisable: "Silenciar sonido",
    pause: "Pausa",
    resume: "Reanudar",
    paused: "En pausa",
    next: "Siguiente",
    round: "Ronda",
    steps: "Escalones",
    you: "Tú",
    needsRival: "A {name} le faltan",
    needsYou: "Te faltan",
    locked: "Número bloqueado",
    lockedHint: "Esperando a los demás…",
    pickPrompt: "Elige tu número",
    pickHint: "← 1 · ↑ 3 · → 5",
    timeLeft: "Tiempo",
    noPick: "Sin número",
    clash: "¡COINCIDÍS!",
    climbs: "sube",
    difficulty: "Dificultad",
    difficulties: {
      facil: "Fácil",
      normal: "Normal",
      dificil: "Difícil",
    },
    difficultyNotes: {
      facil: "Rivales despistados: repiten manías y casi no te leen.",
      normal: "Rivales con carácter propio y buen instinto en la recta final.",
      dificil: "Rivales que te leen, se reparten los números y bloquean tu remate.",
    },
    menuLead:
      "Doce escalones y cuatro escaladores. Cada ronda tienes 10 segundos para elegir 1, 3 o 5 en secreto; después se enseñan a la vez. Quien saque un número que no repita nadie sube esos escalones, y quien coincida se queda donde está.",
    menuTip:
      "El 5 sube más, pero es el que más gente quiere. Mira lo que sacó cada rival en las últimas rondas: acertar dónde no van a estar renta mucho más que gastar una ronda en bloquear a uno, porque bloquear a uno regala la ronda a los otros dos.",
    statusMenu: "Elige dificultad y empieza",
    statusLost: "Llegaron antes que tú",
    revealLead: "Se enseñan los números",
    climbLead: "A subir",
    winnerYou: "¡Has ganado!",
    winnerOther: "gana la escalera",
    winnerTie: "¡Empate en la cima!",
    loseLead: "Llegaron antes que tú.",
    finalRounds: "Rondas jugadas",
    bestRounds: "Mejor victoria",
    wins: "Victorias",
    rounds: "rondas",
    picksHistory: "Últimos números",
    personalities: {
      equilibrio: "Equilibrio",
      impulsivo: "Impulsiva",
      prudente: "Prudente",
      lector: "Lectora",
    },
    personalityNotes: {
      equilibrio: "Reparte sus números como manda la teoría.",
      impulsivo: "Se lanza al 5 en cuanto se ve por detrás.",
      prudente: "Prefiere el 1 y el 3 seguros antes que arriesgar.",
      lector: "Mira lo que sueles sacar y va a bloquearte.",
    },
    rivalNames: {
      p1: "Nora",
      p2: "Bruno",
      p3: "Lía",
    },
    hint:
      "Cada ronda tienes 10 s para elegir 1, 3 o 5 (←/↑/→ o las teclas 1, 3 y 5; también puedes tocar las cartas). Los números repetidos no suben a nadie. El primero en llegar al escalón 12 gana. P pausa, R reinicia, M sonido y F pantalla completa.",
  },
  en: {
    title: "Step by Step",
    subtitle: "Pick 1, 3 or 5. If nobody else picks your number, you climb that many steps.",
    start: "Start",
    again: "Again",
    restart: "Restart",
    changeSetup: "Change difficulty",
    fullscreen: "Fullscreen",
    soundOn: "Sound ON",
    soundOff: "Sound OFF",
    soundEnable: "Enable sound",
    soundDisable: "Mute sound",
    pause: "Pause",
    resume: "Resume",
    paused: "Paused",
    next: "Next",
    round: "Round",
    steps: "Steps",
    you: "You",
    needsRival: "{name} needs",
    needsYou: "You need",
    locked: "Number locked",
    lockedHint: "Waiting for the others…",
    pickPrompt: "Pick your number",
    pickHint: "← 1 · ↑ 3 · → 5",
    timeLeft: "Time",
    noPick: "No pick",
    clash: "CLASH!",
    climbs: "climbs",
    difficulty: "Difficulty",
    difficulties: {
      facil: "Easy",
      normal: "Normal",
      dificil: "Hard",
    },
    difficultyNotes: {
      facil: "Distracted rivals: they repeat their habits and barely read you.",
      normal: "Rivals with their own character and a good nose near the top.",
      dificil: "Rivals that read you, split the numbers, and block your finish.",
    },
    menuLead:
      "Twelve steps and four climbers. Each round you get 10 seconds to secretly pick 1, 3 or 5; then everyone reveals at once. Anyone whose number nobody else picked climbs that many steps, and anyone who clashed stays put.",
    menuTip:
      "5 climbs fastest, but it is also what everyone wants. Watch what each rival picked in recent rounds: guessing where they will not be pays far better than spending a round blocking one of them, because blocking one hands the round to the other two.",
    statusMenu: "Choose a difficulty and start",
    statusLost: "They got there before you",
    revealLead: "Numbers revealed",
    climbLead: "Climbing",
    winnerYou: "You win!",
    winnerOther: "wins the staircase",
    winnerTie: "A tie at the top!",
    loseLead: "They got there before you.",
    finalRounds: "Rounds played",
    bestRounds: "Best win",
    wins: "Wins",
    rounds: "rounds",
    picksHistory: "Recent numbers",
    personalities: {
      equilibrio: "Balanced",
      impulsivo: "Impulsive",
      prudente: "Cautious",
      lector: "Reader",
    },
    personalityNotes: {
      equilibrio: "Splits her numbers exactly the way theory says.",
      impulsivo: "Throws himself at 5 the moment he falls behind.",
      prudente: "Prefers a safe 1 or 3 over a gamble.",
      lector: "Watches what you tend to pick and goes to block it.",
    },
    rivalNames: {
      p1: "Nora",
      p2: "Bruno",
      p3: "Lia",
    },
    hint:
      "Each round you get 10s to pick 1, 3 or 5 (←/↑/→ or the 1, 3 and 5 keys; you can also tap the cards). Repeated numbers move nobody. First to step 12 wins. P pauses, R restarts, M sound, and F toggles fullscreen.",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}

export default getCopy;
