// Bilingual UI copy for Ping Pong Arena.

export const COPY = {
  es: {
    title: "Ping Pong Arena",
    subtitle: "Tenis de mesa en primera persona: la pala es tu dedo.",
    difficulty: "Dificultad",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    format: "Formato",
    best1: "1 set",
    best3: "Al mejor de 3",
    best5: "Al mejor de 5",
    start: "Empezar",
    again: "Otra vez",
    serve: "Saca",
    pause: "Pausa",
    resume: "Reanudar",
    restart: "Reiniciar",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido",
    soundOff: "Silencio",
    soundLabel: "Activar o desactivar el sonido",
    you: "Tú",
    cpu: "CPU",
    sets: "Sets",
    yourServe: "Tu saque — desliza hacia delante para sacar",
    cpuServe: "Saque de la CPU",
    matchWon: "¡Partido ganado!",
    matchLost: "Partido perdido",
    setWon: "Set ganado",
    setLost: "Set perdido",
    tapToServe: "Desliza la pala hacia delante para sacar",
    hint:
      "Mueve la pala con el dedo o el ratón: es tu mano en la mesa. Empújala hacia delante para golpear; cuanto más rápido la lances, más potente y más raso sale el golpe, y si la cruzas en diagonal la bola se abre. Teclado: flechas mueven la pala, Espacio saca. M activa o desactiva el sonido.",
    paused: "Pausa",
  },
  en: {
    title: "Table Tennis Arena",
    subtitle: "First-person table tennis: your finger is the paddle.",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    format: "Format",
    best1: "1 set",
    best3: "Best of 3",
    best5: "Best of 5",
    start: "Start",
    again: "Again",
    serve: "Serve",
    pause: "Pause",
    resume: "Resume",
    restart: "Restart",
    fullscreen: "Fullscreen",
    soundOn: "Sound",
    soundOff: "Muted",
    soundLabel: "Turn the sound on or off",
    you: "You",
    cpu: "CPU",
    sets: "Sets",
    yourServe: "Your serve — flick forward to serve",
    cpuServe: "CPU serve",
    matchWon: "Match won!",
    matchLost: "Match lost",
    setWon: "Set won",
    setLost: "Set lost",
    tapToServe: "Flick the paddle forward to serve",
    hint:
      "Move the bat with your finger or mouse — it is your hand on the table. Push it forward to hit: the harder you drive it, the faster and flatter the shot, and cutting across it sends the ball wide. Keyboard: arrows move the bat, Space serves. M turns the sound on or off.",
    paused: "Paused",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}
