// Bilingual UI copy for Caída Libre (Free Fall).

export const COPY = {
  es: {
    title: "Caída libre",
    subtitle: "Dos trampillas, una buena. Cae dos veces y se acabó tu vuelo.",
    start: "Comenzar",
    again: "Otra vez",
    restart: "Reiniciar",
    changeSetup: "Cambiar dificultad",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido ON",
    soundOff: "Sonido OFF",
    soundEnable: "Activar sonido",
    soundDisable: "Silenciar sonido",
    pause: "Pausa",
    resume: "Reanudar",
    paused: "En pausa",
    menuStatus: "Elige dificultad y empieza",
    chooseSide: "Elige trampilla",
    platform: "Plataforma",
    left: "Izquierda",
    right: "Derecha",
    strikes: "Caídas",
    time: "Tiempo",
    score: "Puntos",
    crowd: "Grupo",
    altitude: "Descenso",
    lockNow: "Fijar elección",
    bravery: "valentía",
    you: "Tú",
    rival: "Rival",
    wins: "Victorias",
    runs: "Intentos",
    out: "Fuera",
    safeStatus: "¡Aguantaste!",
    fellStatus: "Te tragó la nube",
    safe: "Firme",
    cloud: "Nube",
    difficulty: "Dificultad",
    difficulties: { facil: "Fácil", normal: "Normal", dificil: "Difícil" },
    difficultyNotes: {
      facil: "Los rivales se colocan pronto y casi no se mueven.",
      normal: "Se lo piensan y alguno cambia de idea a última hora.",
      dificil: "Tardan en decidirse y se dispersan: poco que leer.",
    },
    menuLead:
      "Tres plataformas y, en cada una, dos trampillas: una aguanta y la otra es una nube. Tienes cinco segundos para colocarte, y puedes cambiarte de lado hasta el último instante. Dos caídas y tu vuelo se acabó.",
    menuTip:
      "No hay forma de saber cuál es la buena: es una moneda al aire y no se puede mejorar. Lo único que puedes decidir es si compartes suerte con la mayoría o te la juegas solo.",
    winLead: "¡Pisaste firme hasta el final!",
    loseLead: "Dos nubes y a tierra.",
    oddsNote: "Sobrevivir las tres plataformas sale 1 de cada 2 veces. Es lo que hay.",
    mechanicTip: "Fija tu elección antes con Espacio para ganar puntos de valentía. No mejora la suerte: renuncias a copiar el último movimiento de los rivales.",
    hint:
      "← y → (o A y D, o tocando cada mitad) para cambiar de trampilla. Espacio abre las trampillas ya. Dos caídas y quedas fuera. P pausa, R reinicia, M sonido y F pantalla completa.",
  },
  en: {
    title: "Free Fall",
    subtitle: "Two trapdoors, one holds. Fall twice and your flight is over.",
    start: "Start",
    again: "Again",
    restart: "Restart",
    changeSetup: "Change difficulty",
    fullscreen: "Fullscreen",
    soundOn: "Sound ON",
    soundOff: "Sound OFF",
    soundEnable: "Enable sound",
    soundDisable: "Mute sound",
    pause: "Pause",
    resume: "Resume",
    paused: "Paused",
    menuStatus: "Choose a difficulty and start",
    chooseSide: "Pick a trapdoor",
    platform: "Platform",
    left: "Left",
    right: "Right",
    strikes: "Falls",
    time: "Time",
    score: "Score",
    crowd: "Crowd",
    altitude: "Descent",
    lockNow: "Lock choice",
    bravery: "bravery",
    you: "You",
    rival: "Rival",
    wins: "Wins",
    runs: "Runs",
    out: "Out",
    safeStatus: "You held!",
    fellStatus: "The cloud swallowed you",
    safe: "Solid",
    cloud: "Cloud",
    difficulty: "Difficulty",
    difficulties: { facil: "Easy", normal: "Normal", dificil: "Hard" },
    difficultyNotes: {
      facil: "The rivals settle early and barely move after that.",
      normal: "They think about it, and one may switch at the last second.",
      dificil: "They take their time and scatter: little to read.",
    },
    menuLead:
      "Three platforms, and on each one two trapdoors: one holds and the other is a cloud. You get five seconds to place yourself, and you can switch sides right up to the last instant. Two falls and your flight is over.",
    menuTip:
      "There is no way to know which one is good: it is a coin toss and no skill improves it. The only thing you decide is whether to share your luck with the crowd or take it on alone.",
    winLead: "Solid ground all the way!",
    loseLead: "Two clouds and down you go.",
    oddsNote: "Surviving all three platforms comes up once in every two runs. That is the game.",
    mechanicTip: "Lock your choice early with Space to earn bravery points. It does not improve your luck: you give up copying the rivals' last move.",
    hint:
      "← and → (or A and D, or tapping each half) switch trapdoor. Space opens the doors early. Two falls and you are out. P pauses, R restarts, M sound, and F toggles fullscreen.",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}

export default getCopy;
