// Bilingual UI copy for Distancia Justa (Right Distance).

export const COPY = {
  es: {
    title: "Distancia Justa",
    subtitle: "Camina la distancia exacta. Los carteles no llegan hasta el final.",
    start: "Empezar",
    chooseDifficulty: "Elige dificultad",
    difficulties: { facil: "Fácil", normal: "Normal", dificil: "Difícil" },
    difficultyHints: {
      facil: "Carteles juntos en pantalla y rivales despistados.",
      normal: "Carteles más separados y rivales decentes.",
      dificil: "Carteles muy separados y rivales de precisión.",
    },
    advance: "Avanzar",
    back: "Atrás",
    confirm: "Confirmar",
    forwardHint: "Mantén para avanzar",
    walkTarget: "¡Avanzad",
    meters: "m",
    time: "Tiempo",
    round: "Ronda",
    best: "Mejor",
    you: "Tú",
    target: "Objetivo",
    yourStop: "Tu parada",
    error: "Diferencia",
    roundResult: "Resultado de ronda",
    points: "pts",
    rankSuffix: "º",
    next: "Siguiente",
    finalStandings: "Clasificación final",
    champion: "¡Campeón!",
    youWin: "¡Ganaste la partida!",
    youPlaced: "Tu puesto",
    again: "Otra vez",
    changeDifficulty: "Cambiar dificultad",
    restart: "Reiniciar",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido ON",
    soundOff: "Sonido OFF",
    soundEnable: "Activar sonido",
    soundDisable: "Silenciar sonido",
    pause: "Pausa",
    resume: "Reanudar",
    paused: "En pausa",
    getReady: "Memoriza la distancia…",
    waiting: "Esperando a los rivales…",
    confirmed: "Confirmado",
    menuLead: "Se anuncia una distancia objetivo. Camina a la derecha: los carteles solo cubren el principio (más separados cuanto mayor la dificultad), luego cuentas a ojo. Para lo más cerca posible antes de que se acabe el tiempo. Compites contra 3 rivales.",
    hint:
      "Se anuncia una distancia (hasta 180 m). Mantén Avanzar (D/→/Espacio o toque en la pista) para caminar, Atrás (A/←) para retroceder y Confirmar (Enter) para fijar tu posición. Los carteles (más separados cuanto más difícil) solo cubren el principio; el resto va a ojo, y al terminar la ronda se revelan las marcas ocultas. 30 s por ronda, 5 rondas, y puntos por puesto frente a 3 IAs. P pausa, R reinicia, M sonido, F pantalla completa.",
  },
  en: {
    title: "Right Distance",
    subtitle: "Walk the exact distance. The signs don't reach the finish.",
    start: "Start",
    chooseDifficulty: "Choose difficulty",
    difficulties: { facil: "Easy", normal: "Normal", dificil: "Hard" },
    difficultyHints: {
      facil: "Signs close together on screen and sloppy rivals.",
      normal: "Signs farther apart and decent rivals.",
      dificil: "Signs far apart and precise rivals.",
    },
    advance: "Advance",
    back: "Back",
    confirm: "Confirm",
    forwardHint: "Hold to walk",
    walkTarget: "Walk",
    meters: "m",
    time: "Time",
    round: "Round",
    best: "Best",
    you: "You",
    target: "Target",
    yourStop: "Your stop",
    error: "Off by",
    roundResult: "Round result",
    points: "pts",
    rankSuffix: "",
    next: "Next",
    finalStandings: "Final standings",
    champion: "Champion!",
    youWin: "You won the match!",
    youPlaced: "You placed",
    again: "Again",
    changeDifficulty: "Change difficulty",
    restart: "Restart",
    fullscreen: "Fullscreen",
    soundOn: "Sound ON",
    soundOff: "Sound OFF",
    soundEnable: "Enable sound",
    soundDisable: "Mute sound",
    pause: "Pause",
    resume: "Resume",
    paused: "Paused",
    getReady: "Memorise the distance…",
    waiting: "Waiting for rivals…",
    confirmed: "Confirmed",
    menuLead: "A target distance is announced. Walk right: the signs only cover the start (spaced wider on harder levels), then you judge by feel. Stop as close as you can before time runs out. You face 3 rivals.",
    hint:
      "A distance is announced (up to 180 m). Hold Advance (D/→/Space or touch the track) to walk, Back (A/←) to step back, and Confirm (Enter) to lock your position. Signs (spaced wider on harder levels) only cover the start; the rest is by feel, and the hidden marks are revealed once the round ends. 30s per round, 5 rounds, and placement points against 3 AIs. P pauses, R restarts, M sound, F fullscreen.",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}

export default getCopy;
