// Bilingual UI copy for Pulso Exacto (Exact Pulse).

export const COPY = {
  es: {
    title: "Pulso Exacto",
    subtitle: "Para el cronómetro justo en el tiempo objetivo. Confía en tu intuición.",
    start: "Empezar",
    startRound: "Comenzar ronda",
    stop: "¡PARAR!",
    next: "Siguiente",
    again: "Otra vez",
    restart: "Reiniciar",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido ON",
    soundOff: "Sonido OFF",
    soundEnable: "Activar sonido",
    soundDisable: "Silenciar sonido",
    pause: "Pausa",
    resume: "Reanudar",
    paused: "En pausa",
    round: "Ronda",
    score: "Puntos",
    best: "Mejor",
    target: "Objetivo",
    yourTime: "Tu tiempo",
    error: "Diferencia",
    late: "tarde",
    early: "pronto",
    roundPoints: "Puntos ronda",
    perfect: "¡PERFECTO!",
    seconds: "s",
    menuLead: "Aparecerá un tiempo objetivo. El cronómetro correrá visible 2 segundos y luego se ocultará: síguelo de memoria y párale lo más cerca posible.",
    readyLead: "Memoriza el objetivo y pulsa para arrancar el cronómetro.",
    watchGuide: "Fíjate en el ritmo…",
    hidden: "Cuenta de memoria y para cuando llegues al objetivo.",
    finalScore: "Puntuación final",
    ratings: {
      swiss: "Reloj suizo",
      master: "Pulso maestro",
      steady: "Buen tempo",
      warming: "Vas cogiendo el ritmo",
      practice: "Sigue practicando",
    },
    hint:
      "Aparece un tiempo objetivo (hasta 60 s). El cronómetro se ve solo los 2 primeros segundos como guía y luego se oculta; párale con Espacio, clic o toque lo más cerca del objetivo. Cuanto menor sea la diferencia, más puntos. 5 rondas por partida. P pausa, R reinicia, M sonido y F pantalla completa.",
  },
  en: {
    title: "Exact Pulse",
    subtitle: "Stop the clock right on the target time. Trust your instinct.",
    start: "Start",
    startRound: "Start round",
    stop: "STOP!",
    next: "Next",
    again: "Again",
    restart: "Restart",
    fullscreen: "Fullscreen",
    soundOn: "Sound ON",
    soundOff: "Sound OFF",
    soundEnable: "Enable sound",
    soundDisable: "Mute sound",
    pause: "Pause",
    resume: "Resume",
    paused: "Paused",
    round: "Round",
    score: "Score",
    best: "Best",
    target: "Target",
    yourTime: "Your time",
    error: "Off by",
    late: "late",
    early: "early",
    roundPoints: "Round points",
    perfect: "PERFECT!",
    seconds: "s",
    menuLead: "A target time appears. The clock runs visibly for 2 seconds and then hides: keep it in your head and stop it as close as you can.",
    readyLead: "Memorise the target and press to start the clock.",
    watchGuide: "Feel the pace…",
    hidden: "Count in your head and stop when you reach the target.",
    finalScore: "Final score",
    ratings: {
      swiss: "Swiss watch",
      master: "Master pulse",
      steady: "Good tempo",
      warming: "Finding the rhythm",
      practice: "Keep practicing",
    },
    hint:
      "A target time appears (up to 60s). The clock is only shown for the first 2 seconds as a guide, then hides; stop it with Space, click or tap as close to the target as you can. The smaller the gap, the more points. 5 rounds per game. P pauses, R restarts, M sound, and F toggles fullscreen.",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}

export default getCopy;
