/**
 * World access for Trayectoria.
 *
 * `world.data.json` is generated by scripts/build-trayectoria-world.mjs. Everything here
 * is lookup and derivation on top of it - no simulation.
 *
 * Crest, league-logo and flag paths point at /assets/football/, which is populated
 * locally by scripts/fetch-football-crests.py and is not committed. Any of them can be
 * null, and a club with no crest simply draws no badge - see `Crest` in index.jsx.
 */

import data from "./world.data.json";

export const world = data;

export const getClub = (id) => data.clubs[id] ?? null;
export const getCompetition = (id) => data.competitions[id] ?? null;
export const getCountry = (fifa) => data.countries[fifa] ?? null;

export const allClubs = () => Object.values(data.clubs);
export const allCompetitions = () => Object.values(data.competitions);
export const allCountries = () => Object.values(data.countries);

/** Countries with at least one modelled league - the ones worth starting a career in. */
export function playableCountries() {
  const withLeague = new Set(
    Object.values(data.competitions).map((competition) => competition.country_fifa_code),
  );
  return Object.values(data.countries)
    .filter((country) => withLeague.has(country.fifa))
    .sort((a, b) => a.name_es.localeCompare(b.name_es));
}

export function clubsOfCompetition(competitionId) {
  return Object.values(data.clubs).filter((club) => club.competitionId === competitionId);
}

export function countryOfClub(clubId) {
  const club = data.clubs[clubId];
  if (!club) return null;
  const competition = data.competitions[club.competitionId];
  return competition ? data.countries[competition.country_fifa_code] ?? null : null;
}

/** Which of black or white reads on a given colour. Rec. 709 luma, nothing cleverer. */
export function readableOn(hex) {
  const value = String(hex).replace("#", "");
  if (value.length !== 6) return "#ffffff";
  const r = parseInt(value.slice(0, 2), 16);
  const g = parseInt(value.slice(2, 4), 16);
  const b = parseInt(value.slice(4, 6), 16);
  // Rec. 709 luma.
  const luma = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
  return luma > 0.6 ? "#0b1220" : "#ffffff";
}

/** How the world is stratified, for the "where do I stand" panel. */
export function reputationCensus() {
  const census = [0, 0, 0, 0, 0, 0];
  for (const club of Object.values(data.clubs)) {
    census[club.international_reputation ?? 0] += 1;
  }
  return census;
}
