// Bilingual UI copy for Saltos Selváticos (Jungle Jaunt).

export const COPY = {
  es: {
    title: "Saltos Selváticos",
    subtitle: "Bálancéate en la liana y suéltate en el momento justo.",
    chooseDifficulty: "Elige dificultad",
    difficulties: { facil: "Fácil", normal: "Normal", dificil: "Difícil" },
    difficultyHints: {
      facil: "Rivales que se sueltan a destiempo y sin apenas impulso.",
      normal: "Rivales que cogen buen vuelo y fallan poco.",
      dificil: "Rivales al límite de la liana y con suelta casi perfecta.",
    },
    menuLead:
      "Cuelgas de una liana sobre el claro. Impulsa el balanceo al pasar por el punto más bajo y suéltate cuando vuelvas a estar a la altura de la plataforma de madera: ahí sale el mejor salto. Balancéate todo lo que quieras… pero la liana es una cuerda: si pasas de la horizontal se destensa y te tira. Tres rondas contra 3 rivales.",
    pump: "Impulsar",
    pumpBack: "Atrás",
    pumpFwd: "Alante",
    jump: "¡Saltar!",
    getReady: "Agárrate a la liana…",
    go: "¡Impulsa!",
    round: "Ronda",
    time: "Tiempo",
    power: "Impulso",
    releaseNow: "¡SUÉLTATE!",
    flying: "¡Volando!",
    waiting: "Esperando a los rivales…",
    meters: "m",
    you: "Tú",
    best: "Récord",
    roundResult: "Resultado de ronda",
    points: "pts",
    rankSuffix: "º",
    next: "Siguiente",
    finalStandings: "Clasificación final",
    youWin: "¡Rey de la selva!",
    again: "Otra vez",
    changeDifficulty: "Cambiar dificultad",
    restart: "Reiniciar",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido ON",
    soundOff: "Sonido OFF",
    soundEnable: "Activar sonido",
    soundDisable: "Silenciar sonido",
    pause: "Pausa",
    resume: "Reanudar",
    paused: "En pausa",
    releaseAngle: "Suelta",
    swingAngle: "Balanceo",
    tooLate: "se le acabó el tiempo",
    scoreboard: "Marcador",
    riskWarn: "¡LA LIANA CEDE!",
    wrongWay: "¡A contramano!",
    slackCue: "¡Liana destensada!",
    slackMsg: "se le destensó la liana",
    hint:
      "◀ y ▶ (flechas, A/D, los botones del panel, o tocar la mitad izquierda/derecha del claro) lanzan tu peso a un lado y a otro: hay que alternarlos con el vaivén. Solo cuenta una pulsación por cada medio balanceo: ◀ mientras vas hacia atrás y ▶ mientras vas hacia delante (el botón que toca se enciende solo). Cae cerca del punto más bajo y rinde el doble; a contramano resta. Machacar no sirve. Enter o J para soltarte. El mejor salto sale al cruzar la altura de la plataforma subiendo hacia delante (marca amarilla). No hay tope de balanceo, pero pasada la horizontal la liana se destensa y te tira: el impulso que te lleva ahí te obliga a saltar en ese mismo balanceo. 3 rondas y puntos por puesto frente a 3 IAs. P pausa, R reinicia, M sonido y F pantalla completa.",
  },
  en: {
    title: "Jungle Jaunt",
    subtitle: "Swing on the vine and let go at exactly the right moment.",
    chooseDifficulty: "Choose difficulty",
    difficulties: { facil: "Easy", normal: "Normal", dificil: "Hard" },
    difficultyHints: {
      facil: "Rivals who mistime the release and barely build momentum.",
      normal: "Rivals with a solid swing who rarely miss.",
      dificil: "Rivals swinging to the limit with a near-perfect release.",
    },
    menuLead:
      "You hang from a vine over the clearing. Pump the swing as you sweep through the lowest point and let go when you're back at the height of the wooden platform: that's where the best jump comes from. Swing as long as you like… but a vine is a rope: push past horizontal and it goes slack and drops you. Three rounds against 3 rivals.",
    pump: "Pump",
    pumpBack: "Back",
    pumpFwd: "Forward",
    jump: "Jump!",
    getReady: "Grab the vine…",
    go: "Swing!",
    round: "Round",
    time: "Time",
    power: "Momentum",
    releaseNow: "LET GO!",
    flying: "Flying!",
    waiting: "Waiting for the rivals…",
    meters: "m",
    you: "You",
    best: "Best",
    roundResult: "Round result",
    points: "pts",
    rankSuffix: "",
    next: "Next",
    finalStandings: "Final standings",
    youWin: "King of the jungle!",
    again: "Again",
    changeDifficulty: "Change difficulty",
    restart: "Restart",
    fullscreen: "Fullscreen",
    soundOn: "Sound ON",
    soundOff: "Sound OFF",
    soundEnable: "Enable sound",
    soundDisable: "Mute sound",
    pause: "Pause",
    resume: "Resume",
    paused: "Paused",
    releaseAngle: "Release",
    swingAngle: "Swing",
    tooLate: "ran out of time",
    scoreboard: "Scoreboard",
    riskWarn: "THE VINE IS GIVING!",
    wrongWay: "Against the swing!",
    slackCue: "Vine went slack!",
    slackMsg: "let the vine go slack",
    hint:
      "◀ and ▶ (arrows, A/D, the deck buttons, or tapping the left/right half of the clearing) throw your weight each way, and you have to alternate them with the swing. Only one press per half-swing counts: ◀ while you travel back and ▶ while you travel forward (the right button lights up on its own). Land it near the bottom of the arc and it pays double; throw against the swing and it costs you. Mashing gets you nowhere. Enter or J lets go. The best jump comes from releasing as you cross the platform's height on the way up and forward (the yellow marker). There's no cap on the swing, but past horizontal the vine goes slack and drops you: the pump that takes you there commits you to jumping on that same swing. 3 rounds and placement points against 3 AIs. P pauses, R restarts, M sound, and F toggles fullscreen.",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}

export default getCopy;
