import { COMPACT_GENERATED_TIMELINE_EVENTS } from "./timelineEventBank.compact.generated.js";

const E = (id, year, tags, titleEs, titleEn, summaryEs, summaryEn) => ({
  id,
  year,
  tags,
  title: { es: titleEs, en: titleEn },
  summary: { es: summaryEs, en: summaryEn },
});

const BASE_TIMELINE_EVENT_BANK = [
  E("olympic-games-olympia", -776, ["culture", "sports"], "Primeros Juegos Olimpicos en Olimpia", "First Olympic Games in Olympia", "Inicio documentado de una competicion atletica panhelenica.", "Documented beginning of the pan-Hellenic athletic competition."),
  E("assassination-julius-caesar", -44, ["geopolitics"], "Asesinato de Julio Cesar", "Assassination of Julius Caesar", "Crisis politica que acelero el final de la Republica romana.", "Political crisis that accelerated the end of the Roman Republic."),
  E("edict-of-milan", 313, ["rights", "geopolitics"], "Edicto de Milan", "Edict of Milan", "Acuerdo imperial que amplio la tolerancia religiosa en Roma.", "Imperial agreement that expanded religious tolerance in Rome."),
  E("fall-western-roman-empire", 476, ["geopolitics", "war"], "Caida del Imperio romano de Occidente", "Fall of the Western Roman Empire", "Deposicion de Romulo Augustulo y cambio de era politica.", "Deposition of Romulus Augustulus and a political era shift."),
  E("hijra", 622, ["culture", "geopolitics"], "Hegira a Medina", "Hijra to Medina", "Migracion que marca el inicio del calendario islamico.", "Migration that marks the beginning of the Islamic calendar."),
  E("charlemagne-coronation", 800, ["geopolitics", "culture"], "Coronacion de Carlomagno", "Coronation of Charlemagne", "Restablecimiento de una autoridad imperial en Europa occidental.", "Re-establishment of imperial authority in Western Europe."),
  E("norman-conquest-england", 1066, ["war", "geopolitics"], "Conquista normanda de Inglaterra", "Norman conquest of England", "Guillermo de Normandia vence en Hastings y toma la corona.", "William of Normandy wins at Hastings and takes the crown."),
  E("magna-carta", 1215, ["rights", "geopolitics"], "Firma de la Carta Magna", "Signing of Magna Carta", "Limite juridico al poder monarquico en Inglaterra.", "Legal limitation of monarchical power in England."),
  E("black-death-europe", 1347, ["medicine", "geopolitics"], "Llegada de la Peste Negra a Europa", "Black Death reaches Europe", "Epidemia con enorme impacto demografico y economico.", "Epidemic with massive demographic and economic impact."),
  E("printing-press-gutenberg", 1450, ["technology", "culture"], "Imprenta de tipos moviles en Europa", "Movable-type printing press in Europe", "Difusion acelerada del conocimiento escrito.", "Accelerated spread of written knowledge."),
  E("fall-constantinople", 1453, ["war", "geopolitics"], "Caida de Constantinopla", "Fall of Constantinople", "El Imperio otomano conquista la capital bizantina.", "The Ottoman Empire captures the Byzantine capital."),
  E("columbus-caribbean", 1492, ["exploration", "geopolitics"], "Viaje de Colon al Caribe", "Columbus reaches the Caribbean", "Inicio de un intercambio transatlantico de gran escala.", "Start of a large-scale transatlantic exchange."),
  E("luther-theses", 1517, ["culture", "geopolitics"], "Publicacion de las 95 tesis", "Publication of the Ninety-five Theses", "Momento clave de la Reforma protestante.", "Key turning point of the Protestant Reformation."),
  E("copernicus-revolutionibus", 1543, ["science"], "Publicacion de De revolutionibus", "Publication of De revolutionibus", "Base de la revolucion astronomica heliocentrica.", "Foundational text for the heliocentric revolution."),
  E("galileo-telescope-observations", 1609, ["science", "technology"], "Observaciones telescopicas de Galileo", "Galileo's telescopic observations", "Uso sistematico del telescopio para estudiar el cielo.", "Systematic telescope use to study the sky."),
  E("newton-principia", 1687, ["science"], "Publicacion de Principia Mathematica", "Publication of Principia Mathematica", "Formalizacion de leyes del movimiento y gravitacion.", "Formalization of laws of motion and gravitation."),
  E("watt-steam-patent", 1769, ["technology", "economy"], "Patente de la maquina de vapor de Watt", "Watt steam engine patent", "Hito tecnico de la mecanizacion industrial.", "Technical milestone for industrial mechanization."),
  E("us-declaration-independence", 1776, ["rights", "geopolitics"], "Declaracion de Independencia de EE. UU.", "US Declaration of Independence", "Ruptura politica con el Reino Unido.", "Political break from the United Kingdom."),
  E("french-revolution", 1789, ["rights", "geopolitics"], "Comienzo de la Revolucion francesa", "Start of the French Revolution", "Transformacion institucional y social de gran impacto.", "Institutional and social transformation with broad impact."),
  E("napoleon-emperor", 1804, ["geopolitics", "war"], "Napoleon se proclama emperador", "Napoleon proclaims himself emperor", "Consolidacion del poder napoleonico en Francia.", "Consolidation of Napoleonic power in France."),
  E("first-public-railway", 1825, ["technology", "economy"], "Primer ferrocarril publico moderno", "First modern public railway", "Apertura de una linea regular de transporte ferroviario.", "Opening of a regular railway transport line."),
  E("morse-telegraph", 1837, ["technology"], "Desarrollo del telegrafo de Morse", "Development of Morse telegraph", "Revolucion en comunicaciones a larga distancia.", "Communication revolution over long distances."),
  E("origin-of-species", 1859, ["science"], "Publicacion de El origen de las especies", "Publication of On the Origin of Species", "Modelo evolutivo por seleccion natural.", "Evolutionary model based on natural selection."),
  E("red-cross-founded", 1863, ["rights", "medicine"], "Fundacion del Comite Internacional de la Cruz Roja", "International Red Cross founded", "Nacimiento de un actor central en accion humanitaria.", "Birth of a central actor in humanitarian response."),
  E("suez-canal-opened", 1869, ["economy", "geopolitics"], "Inauguracion del canal de Suez", "Opening of the Suez Canal", "Nueva ruta estrategica entre Mediterraneo y Mar Rojo.", "New strategic route between the Mediterranean and Red Sea."),
  E("telephone-patent", 1876, ["technology"], "Patente del telefono de Bell", "Bell telephone patent", "Hito en comunicaciones de voz por red cableada.", "Milestone in wired voice communications."),
  E("eiffel-tower-opened", 1889, ["culture", "art"], "Apertura de la Torre Eiffel", "Opening of the Eiffel Tower", "Icono de ingenieria y exposiciones universales.", "Icon of engineering and world expositions."),
  E("xray-discovery", 1895, ["science", "medicine"], "Descubrimiento de los rayos X", "Discovery of X-rays", "Tecnica fundamental para diagnostico medico por imagen.", "Foundational technique for diagnostic imaging."),
  E("first-modern-olympics", 1896, ["sports", "culture"], "Primeros Juegos Olimpicos modernos", "First modern Olympic Games", "Reinicio del movimiento olimpico internacional en Atenas.", "International Olympic movement relaunched in Athens."),
  E("wright-first-flight", 1903, ["technology"], "Primer vuelo controlado de los hermanos Wright", "Wright brothers' first controlled flight", "Inicio de la aviacion motorizada de ala fija.", "Beginning of powered fixed-wing aviation."),
  E("einstein-annus-mirabilis", 1905, ["science"], "Anno mirabilis de Einstein", "Einstein annus mirabilis papers", "Trabajos clave en relatividad y efecto fotoelectrico.", "Key works on relativity and photoelectric effect."),
  E("world-war-one-start", 1914, ["war", "geopolitics"], "Inicio de la Primera Guerra Mundial", "Start of World War I", "Escalada global de alianzas y frentes belicos.", "Global escalation of alliances and war fronts."),
  E("russian-revolution", 1917, ["geopolitics", "rights"], "Revolucion rusa", "Russian Revolution", "Caida del regimen zarista y nuevo ciclo politico.", "Fall of tsarist rule and a new political cycle."),
  E("league-of-nations", 1920, ["geopolitics"], "Entrada en vigor de la Sociedad de Naciones", "League of Nations enters into force", "Intento multilateral de prevenir nuevas guerras mundiales.", "Multilateral attempt to prevent future world wars."),
  E("insulin-first-treatment", 1922, ["medicine", "science"], "Primer tratamiento clinico con insulina", "First clinical treatment with insulin", "Avance decisivo en el control de la diabetes.", "Decisive advance in diabetes management."),
  E("jazz-singer-talkie", 1927, ["media", "culture"], "Estreno de The Jazz Singer", "Release of The Jazz Singer", "Pelicula de referencia en la transicion al cine sonoro.", "Landmark film in the transition to sound cinema."),
  E("penicillin-discovery", 1928, ["medicine", "science"], "Descubrimiento de la penicilina", "Discovery of penicillin", "Base de la era antibiotica en medicina moderna.", "Foundation of the antibiotic era in medicine."),
  E("wall-street-crash", 1929, ["economy", "geopolitics"], "Crac de Wall Street", "Wall Street crash", "Colapso financiero que desencadeno la Gran Depresion.", "Financial collapse that triggered the Great Depression."),
  E("first-fifa-world-cup", 1930, ["sports", "culture"], "Primera Copa Mundial de Futbol", "First FIFA World Cup", "Inicio del principal torneo internacional de selecciones.", "Beginning of the leading international national-team tournament."),
  E("world-war-two-start", 1939, ["war", "geopolitics"], "Inicio de la Segunda Guerra Mundial", "Start of World War II", "Expansion del conflicto a escala global.", "Conflict expansion to global scale."),
  E("hiroshima-bombing", 1945, ["war", "science"], "Bombardeo atomico de Hiroshima", "Atomic bombing of Hiroshima", "Uso belico de arma nuclear con consecuencias humanas masivas.", "Wartime nuclear weapon use with massive human consequences."),
  E("universal-declaration-human-rights", 1948, ["rights", "geopolitics"], "Declaracion Universal de Derechos Humanos", "Universal Declaration of Human Rights", "Marco internacional de derechos fundamentales.", "International framework for fundamental rights."),
  E("nato-founded", 1949, ["geopolitics", "war"], "Fundacion de la OTAN", "NATO founded", "Alianza militar clave del orden de posguerra.", "Key military alliance in the postwar order."),
  E("dna-double-helix", 1953, ["science", "medicine"], "Descripcion de la estructura del ADN", "Description of DNA structure", "Paso central para la biologia molecular moderna.", "Core step for modern molecular biology."),
  E("warsaw-pact", 1955, ["geopolitics", "war"], "Creacion del Pacto de Varsovia", "Creation of the Warsaw Pact", "Bloque militar del este durante la Guerra Fria.", "Eastern military bloc during the Cold War."),
  E("sputnik-launch", 1957, ["space", "science"], "Lanzamiento del Sputnik 1", "Launch of Sputnik 1", "Primer satelite artificial en orbita terrestre.", "First artificial satellite in Earth orbit."),
  E("gagarin-orbit", 1961, ["space", "science"], "Yuri Gagarin completa orbita tripulada", "Yuri Gagarin completes crewed orbit", "Primer vuelo espacial humano alrededor de la Tierra.", "First human spaceflight around Earth."),
  E("moon-landing-apollo11", 1969, ["space", "science"], "Llegada del Apolo 11 a la Luna", "Apollo 11 Moon landing", "Primer alunizaje tripulado de la historia.", "First crewed moon landing in history."),
  E("intel-4004", 1971, ["technology"], "Lanzamiento del microprocesador Intel 4004", "Launch of Intel 4004 microprocessor", "Componente clave para la computacion personal posterior.", "Key component for later personal computing."),
  E("oil-crisis-1973", 1973, ["economy", "geopolitics"], "Crisis del petroleo de 1973", "1973 oil crisis", "Choque energetico con efectos economicos globales.", "Energy shock with global economic effects."),
  E("apple-founded", 1976, ["technology", "economy"], "Fundacion de Apple", "Apple founded", "Nueva etapa en computacion personal de consumo.", "New chapter in consumer personal computing."),
  E("star-wars-release", 1977, ["culture", "media"], "Estreno de Star Wars", "Release of Star Wars", "Fenomeno cultural global en la industria audiovisual.", "Global cultural phenomenon in audiovisual media."),
  E("tcp-ip-transition", 1983, ["technology"], "Transicion de ARPANET a TCP/IP", "ARPANET transition to TCP/IP", "Estandar de red esencial para la Internet moderna.", "Core network standard for the modern Internet."),
  E("chernobyl-disaster", 1986, ["science", "geopolitics"], "Accidente de Chernobil", "Chernobyl disaster", "Crisis nuclear con efectos sanitarios y politicos duraderos.", "Nuclear crisis with long-term health and political effects."),
  E("berlin-wall-fall", 1989, ["geopolitics", "rights"], "Caida del Muro de Berlin", "Fall of the Berlin Wall", "Simbolo del fin de la division bipolar en Europa.", "Symbol of the end of bipolar division in Europe."),
  E("soviet-union-dissolution", 1991, ["geopolitics"], "Disolucion de la URSS", "Dissolution of the USSR", "Reconfiguracion geopolitica del espacio euroasiatico.", "Geopolitical reconfiguration of Eurasia."),
  E("mandela-presidency", 1994, ["rights", "geopolitics"], "Nelson Mandela presidente de Sudafrica", "Nelson Mandela becomes president of South Africa", "Transicion democratica tras el fin del apartheid.", "Democratic transition after apartheid."),
  E("wto-founded", 1995, ["economy", "geopolitics"], "Creacion de la OMC", "World Trade Organization created", "Nuevo marco multilateral para reglas del comercio.", "New multilateral framework for trade rules."),
  E("google-founded", 1998, ["technology", "economy"], "Fundacion de Google", "Google founded", "Escalado masivo de busqueda y publicidad en Internet.", "Massive scaling of web search and online advertising."),
  E("wikipedia-launched", 2001, ["technology", "culture"], "Lanzamiento de Wikipedia", "Wikipedia launched", "Modelo colaborativo de conocimiento abierto en linea.", "Collaborative open-knowledge model online."),
  E("euro-cash", 2002, ["economy", "geopolitics"], "Entrada en circulacion del euro fisico", "Euro cash enters circulation", "Integracion monetaria visible para millones de ciudadanos.", "Visible monetary integration for millions of citizens."),
  E("human-genome-project", 2003, ["science", "medicine"], "Final del Proyecto Genoma Humano", "Human Genome Project completed", "Mapa de referencia para genetica y medicina de precision.", "Reference map for genetics and precision medicine."),
  E("youtube-launch", 2005, ["technology", "media"], "Lanzamiento de YouTube", "YouTube launched", "Plataforma que reconfiguro distribucion de video online.", "Platform that reshaped online video distribution."),
  E("iphone-launch", 2007, ["technology", "economy"], "Presentacion del iPhone", "iPhone unveiled", "Aceleracion del ecosistema smartphone y apps moviles.", "Acceleration of the smartphone and app ecosystem."),
  E("global-financial-crisis", 2008, ["economy", "geopolitics"], "Crisis financiera global de 2008", "Global financial crisis of 2008", "Recesion internacional con reformas regulatorias posteriores.", "International recession followed by regulatory reforms."),
  E("arab-spring", 2010, ["geopolitics", "rights"], "Comienzo de la Primavera Arabe", "Beginning of the Arab Spring", "Movilizaciones sociales y cambios politicos en varios paises.", "Social mobilizations and political shifts across multiple countries."),
  E("higgs-boson-confirmed", 2012, ["science"], "Confirmacion del boson de Higgs", "Higgs boson confirmed", "Resultado experimental clave de fisica de particulas.", "Key experimental result in particle physics."),
  E("paris-climate-agreement", 2015, ["geopolitics", "science"], "Acuerdo de Paris sobre clima", "Paris climate agreement", "Compromiso internacional para limitar el calentamiento global.", "International commitment to limit global warming."),
  E("gravitational-waves-detected", 2016, ["science", "space"], "Deteccion de ondas gravitacionales", "Detection of gravitational waves", "Nueva ventana observacional para la astrofisica.", "New observational window for astrophysics."),
  E("black-hole-image", 2019, ["science", "space"], "Primera imagen de un agujero negro", "First image of a black hole", "Hito de colaboracion cientifica global en radioastronomia.", "Global collaboration milestone in radio astronomy."),
  E("who-pandemic-declaration", 2020, ["medicine", "geopolitics"], "Declaracion de pandemia por la OMS", "WHO declares a global pandemic", "Reconocimiento oficial de una emergencia sanitaria mundial.", "Official recognition of a worldwide health emergency."),
  E("james-webb-first-deep-field", 2022, ["space", "science"], "Primer deep field del telescopio James Webb", "James Webb first deep field image", "Nueva etapa en observacion infrarroja del universo.", "New stage in infrared observation of the universe."),
];

export const TIMELINE_EVENT_BANK = [
  ...BASE_TIMELINE_EVENT_BANK,
  ...COMPACT_GENERATED_TIMELINE_EVENTS,
];
