// Textos bilingües de Pádel Pro Arena.

export const COPY = {
  es: {
    title: "Pádel Pro Arena",
    subtitle: "Pádel por parejas en pseudo-3D: coloca, golpea y juega las paredes.",
    difficulty: "Dificultad",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    easyDesc: "Rivales pausados: ideal para coger el punto.",
    mediumDesc: "Ritmo equilibrado y buena colocación.",
    hardDesc: "Rivales rápidos y agresivos en la red.",
    format: "Formato",
    best1: "1 set",
    best3: "Al mejor de 3",
    best1Desc: "Partida corta",
    best3Desc: "Partido completo",
    howTo: "Cómo se juega",
    start: "Empezar partido",
    again: "Otra vez",
    serve: "Sacar",
    hit: "Golpear",
    shotVolea: "Volea",
    shotReves: "Revés",
    shotGlobo: "Globo",
    shotDejada: "Dejada",
    shotsLabel: "Golpes",
    pause: "Pausa",
    resume: "Reanudar",
    restart: "Reiniciar",
    fullscreen: "Pantalla completa",
    soundOn: "Sonido",
    soundOff: "Silencio",
    soundLabel: "Activar o desactivar el sonido",
    you: "Tú",
    cpu: "CPU",
    sets: "Sets",
    games: "Juegos",
    hudSet: "SET",
    hudGame: "JUEGO",
    hudPoint: "PUNTO",
    hudTie: "TIE-BREAK",
    yourServe: "Tu saque — pulsa Sacar",
    cpuServe: "Saque rival",
    tieBreak: "Tie-break",
    matchWon: "¡Partido ganado!",
    matchLost: "Partido perdido",
    setWon: "Set ganado",
    setLost: "Set perdido",
    gameWon: "¡Juego para ti!",
    gameLost: "Juego para el rival",
    point: "Punto",
    pointForYou: "¡Punto para ti!",
    pointForCpu: "Punto para el rival",
    hint:
      "Muévete con las flechas/joystick y elige tu golpe con los botones o las teclas: Volea (F/Espacio) es el ataque natural (remate/víbora si la bola llega alta a la red), Revés (G), Globo (H) y Dejada (J). Mantén pulsado el golpe para cargar potencia: la barra sobre tu figura marca cuánta llevas y el golpe sale al contactar con la bola, así que puedes armar antes de que llegue. A tope va más al fondo y más rápido, pero abre un poco la colocación. La dejada es de toque y no carga. Marca dirección al golpear para colocar la bola. Cuanto mejor el contacto (centrado y a buena altura), más profundo y preciso; las liftadas pican bajas y las cortadas se sientan. El globo sobrevuela a los de la red; tras botar puedes jugar la pared de cristal. Saca cruzado por debajo. P pausa, R reinicia, M sonido y el botón de arriba pantalla completa.",
    paused: "Pausa",
  },
  en: {
    title: "Padel Pro Arena",
    subtitle: "Pseudo-3D doubles padel: position, strike and play the walls.",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    easyDesc: "Relaxed rivals: great to find your timing.",
    mediumDesc: "Balanced pace and solid placement.",
    hardDesc: "Fast rivals, aggressive at the net.",
    format: "Format",
    best1: "1 set",
    best3: "Best of 3",
    best1Desc: "Quick game",
    best3Desc: "Full match",
    howTo: "How to play",
    start: "Start match",
    again: "Again",
    serve: "Serve",
    hit: "Hit",
    shotVolea: "Volley",
    shotReves: "Backhand",
    shotGlobo: "Lob",
    shotDejada: "Drop",
    shotsLabel: "Shots",
    pause: "Pause",
    resume: "Resume",
    restart: "Restart",
    fullscreen: "Fullscreen",
    soundOn: "Sound",
    soundOff: "Muted",
    soundLabel: "Turn the sound on or off",
    you: "You",
    cpu: "CPU",
    sets: "Sets",
    games: "Games",
    hudSet: "SET",
    hudGame: "GAME",
    hudPoint: "POINT",
    hudTie: "TIE-BREAK",
    yourServe: "Your serve — press Serve",
    cpuServe: "Opponent serve",
    tieBreak: "Tie-break",
    matchWon: "Match won!",
    matchLost: "Match lost",
    setWon: "Set won",
    setLost: "Set lost",
    gameWon: "Game to you!",
    gameLost: "Game to the rivals",
    point: "Point",
    pointForYou: "Point for you!",
    pointForCpu: "Point for the rivals",
    hint:
      "Move with the arrows/joystick and pick your shot with the buttons or keys: Volley (F/Space) is the natural attack (smash/víbora if the ball comes high at the net), Backhand (G), Lob (H) and Drop (J). Hold the shot down to charge power: the bar above your figure shows how much, and the shot fires on contact, so you can wind up before the ball arrives. Fully charged goes deeper and faster but opens up your placement a little. The drop shot is a touch shot and does not charge. Hold a direction as you hit to place the ball. The cleaner the contact (centred and at a good height), the deeper and more accurate; topspin skids low and backspin sits up. The lob sails over the net players; after a bounce you can play the glass wall. Serve cross-court, underhand. P pauses, R restarts, M sound, and the top button toggles fullscreen.",
    paused: "Paused",
  },
};

export function getCopy(locale) {
  return COPY[locale] ?? COPY.en;
}
