/**
 * Todo el texto del juego, es/en (§13).
 *
 * THE RULE THAT GOVERNS EVERYTHING: no string lives in a component. Dialogue, technique
 * names, dossier reports, press headlines, buttons, error messages, control hints — all of
 * it here, with the same key in `es` and in `en`, and `copy.test.js` standing over it from
 * the first line rather than the last.
 *
 * THE ENGLISH IS AN ADAPTATION, NOT A TRANSLATION (§13.2). Concretely:
 *
 *  - Marés stays Marés. The districts keep their names — Puerto Viejo, La Concha, Cerro
 *    del Faro — because they are toponyms and toponyms are not translated. The game is
 *    Spanish and that is the point of it.
 *  - The cast keeps their names. Dani Vela is Dani Vela in both. An English-speaking player
 *    does not need to be told "Danny".
 *  - Technique names are hissatsu names: they have to SOUND RIGHT SHOUTED, not be exact.
 *    *Puño de Tormenta* → **Thunderfist**, not "Storm Fist", which is correct and sounds
 *    like nothing. *Vaho* → **Blackout Step**. *Lectura* → **Tell**, borrowing the poker
 *    term, because that is what the technique actually does. Each one was approved on how
 *    it sounds, not on how literal it is.
 *  - Sabater's reports are written twice, in real police register in each language, because
 *    Spanish police prose and English police prose are different genres.
 *  - Doña Pilar has no English equivalent, so `en` carries the name plus a register that
 *    does the same work — the respectful distance survives, the honorific does not.
 *
 * TEMPLATES, NEVER CONCATENATION (§13.3). `{n}` and `{quien}` sit inside the string so the
 * word order can differ. Counted lines carry both forms per language; Spanish agrees in
 * gender and English does not, so there is no shared plural rule and there must not be one.
 */

/* ── Utilidades ──────────────────────────────────────────────────────────────────── */

/** `"Le faltan {n} pruebas"` + `{n: 2}` → `"Le faltan 2 pruebas"`. */
export function fillTemplate(template, values = {}) {
  if (typeof template !== "string") return "";
  return template.replace(/\{(\w+)\}/g, (match, key) => (values[key] !== undefined ? String(values[key]) : match));
}

/** Picks the singular at exactly one, in both directions. */
export function countOf(one, many, n) {
  return Math.abs(n) === 1 ? one : many;
}

const COPY = {
  es: {
    /* ── Identidad ───────────────────────────────────────────────────────────────── */
    meta: {
      titulo: "FULGOR",
      lema: "Tienes quince años, tienes el rayo y tienes dos vidas que no pueden tocarse.",
      subtitulo: "Marés · un action-RPG de doble vida",
      autoria: "Un juego sobre sostener una mentira.",
    },

    /* ── Interfaz general ────────────────────────────────────────────────────────── */
    ui: {
      empezar: "Empezar",
      partidaNueva: "Partida nueva",
      continuar: "Continuar",
      importarCodigo: "Importar código",
      volver: "Volver",
      cerrar: "Cerrar",
      aceptar: "Aceptar",
      cancelar: "Cancelar",
      siguiente: "Siguiente",
      confirmar: "Confirmar",
      guardar: "Guardar",
      opciones: "Opciones",
      creditos: "Créditos",
      pausa: "Pausa",
      saltar: "Saltar",
      idioma: "Idioma",
      dificultad: "Dificultad",
      expedientes: "Expedientes",
      traje: "Traje",
      tecnicas: "Técnicas",
      mapa: "Mapa",
      diario: "Diario",
      sinDatos: "Todavía no hay nada aquí.",
      cargando: "Cargando…",

      /* El mundo caminable: la pantalla de abajo ya no ofrece acciones, informa y manda. */
      capitulo: "Capítulo",
      dia: "Día",
      mover: "Mover",
      hablar: "Hablar",
      entrar: "Entrar",
      nadaCerca: "Nada cerca",
      seHaceDeNoche: "Se acaba el día",
    },

    /* ── Los dos recursos y las siete estadísticas ───────────────────────────────── */
    recursos: {
      carga: "Carga",
      compostura: "Compostura",
      cargaAyuda: "La batería. Se gasta con cada técnica y se rellena tocando corriente.",
      composturaAyuda: "El aguante físico y nervioso. Cuando baja, no sólo fallas: te ven.",
      rango: "Rango",
      rangoAyuda: "Lo que Marés cree saber de ti. Sube contigo — y con ella sube Sabater.",
      dinero: "Dinero",
      nivel: "Nivel",
      xp: "Experiencia",
      puntosLibres: "Puntos por repartir",
    },
    stats: {
      potencia: "Potencia",
      cuerpo: "Cuerpo",
      control: "Control",
      guardia: "Guardia",
      velocidad: "Velocidad",
      aguante: "Aguante",
      temple: "Temple",
    },
    statsAyuda: {
      potencia: "Daño de las técnicas de Impacto.",
      cuerpo: "Resistir agarres, empujar, aguantar golpes.",
      control: "Precisión: acertar sin destrozar el entorno.",
      guardia: "Reduce el daño recibido y el desgaste del traje.",
      velocidad: "Coste en turnos de las rutas e iniciativa en el duelo.",
      aguante: "Carga máxima y regeneración por turno.",
      temple: "Compostura máxima; resistencia al miedo y al dolor.",
    },

    /* ── Afinidades ──────────────────────────────────────────────────────────────── */
    afinidades: { rayo: "Rayo", luz: "Luz", sombra: "Sombra", materia: "Materia" },
    afinidadesAyuda: {
      rayo: "Fuerza bruta eléctrica: impacto, aturdimiento, sobrecarga.",
      luz: "Percepción: cegar, iluminar, revelar. Lo contrario de esconderse.",
      sombra: "Ocultación, silencio, apagar. Bajísima visibilidad.",
      materia: "Lo físico y lo mecánico: metal, estructuras, máquinas.",
    },
    afinidadVentaja: "{atacante} tiene ventaja sobre {defensor}.",
    afinidadDesventaja: "{atacante} lo tiene difícil contra {defensor}.",

    /* ── Familias de técnica ─────────────────────────────────────────────────────── */
    familias: {
      impacto: "Impacto",
      velocidad: "Velocidad",
      luz: "Luz",
      escudo: "Escudo",
      sentido: "Sentido",
    },
    familiasAyuda: {
      impacto: "Resolver un duelo por la fuerza.",
      velocidad: "Moverse gratis, ganar iniciativa, huir.",
      luz: "Cegar, revelar, ver a través, distraer.",
      escudo: "Absorber, proteger a un civil, aguantar.",
      sentido: "No hace daño. Compra información, que es lo que de verdad se gana aquí.",
    },

    /* ── Las cuarenta técnicas ───────────────────────────────────────────────────── */
    tecnicas: {
      chispazo: "Chispazo",
      arcoVoltaico: "Arco Voltaico",
      punoTormenta: "Puño de Tormenta",
      yunque: "Yunque",
      sobrecarga: "Sobrecarga",
      truenoSeco: "Trueno Seco",
      martillo: "Martillo",
      chispaFria: "Chispa Fría",
      descargaCero: "Descarga Cero",
      pasoCorto: "Paso Corto",
      relampago: "Relámpago",
      vaho: "Vaho",
      fuga: "Fuga",
      estela: "Estela",
      cortocircuito: "Cortocircuito",
      sombraLarga: "Sombra Larga",
      destello: "Destello",
      espejismo: "Espejismo",
      prisma: "Prisma",
      fulgor: "Fulgor",
      cortina: "Cortina",
      aurora: "Aurora",
      reflejo: "Reflejo",
      alba: "Alba",
      pararrayos: "Pararrayos",
      malla: "Malla",
      aguanteTec: "Aguante",
      jaula: "Jaula",
      tierra: "Tierra",
      cupula: "Cúpula",
      ancla: "Ancla",
      escucha: "Escucha",
      lectura: "Lectura",
      barrido: "Barrido",
      pulso: "Pulso",
      anticipo: "Anticipo",
      silencio: "Silencio",
      rastro: "Rastro",
      eco: "Eco",
      presagio: "Presagio",
    },
    tecnicasAyuda: {
      chispazo: "Daño bajo, fiable. La primera cosa que aprendiste a hacer a propósito.",
      arcoVoltaico: "Daño alto y alcanza a dos. Se ve desde la otra acera.",
      punoTormenta: "Si acierta, el duelo se acabó. Y todo el mundo sabrá que estuviste ahí.",
      yunque: "Derriba lo que sostiene el nodo.",
      sobrecarga: "Inutiliza cualquier aparato que tenga corriente dentro.",
      truenoSeco: "Corto, seco y sin florituras. Hierro te enseñó que eso también vale.",
      martillo: "Ignora la guardia. No hay postura que aguante esto.",
      chispaFria: "Luz que golpea sin quemar: hace daño y casi no se ve.",
      descargaCero: "Todo lo que tienes, de una vez, y en silencio.",
      pasoCorto: "Un nodo, sin gastar turno.",
      relampago: "Medio escenario al instante. Y una línea de luz que apunta a dónde ibas.",
      vaho: "Rompe el duelo sin dejar rastro.",
      fuga: "Escapas y, de paso, borras una pista Testimonial.",
      estela: "Ganas la iniciativa del próximo turno.",
      cortocircuito: "Deja el nodo entero sin corriente.",
      sombraLarga: "Cruzas el escenario por donde no hay luz que te dibuje.",
      destello: "Ciega: el rival pierde el turno. También lo ve la calle entera.",
      espejismo: "Los testigos ven a otro. Ninguno miente al declarar.",
      prisma: "Divide un ataque entre tres rivales.",
      fulgor: "Resuelve todos los duelos del nodo. Y sale en todas las cámaras.",
      cortina: "Apaga todas las luces del nodo.",
      aurora: "Una cortina de luz que barre a dos.",
      reflejo: "Devuelve el próximo ataque por donde vino.",
      alba: "Lo revela todo: cámaras, testigos, salidas, rutas.",
      pararrayos: "Absorbe el próximo ataque y lo convierte en Carga.",
      malla: "Protege a un civil durante dos turnos.",
      aguanteTec: "Recuperas Compostura. Respirar también es una técnica.",
      jaula: "Inmoviliza sin dañar. Contener, pero bien.",
      tierra: "Anula la ventaja de afinidad del rival.",
      cupula: "Protege el nodo entero durante un turno.",
      ancla: "No hay agarre que te mueva.",
      escucha: "Revela a los adversarios de los nodos vecinos.",
      lectura: "Enseña qué va a hacer el rival en el próximo turno.",
      barrido: "Marca todas las cámaras y todos los testigos del escenario.",
      pulso: "Muestra el plano completo, incluidas las rutas ocultas.",
      anticipo: "+25% de éxito en tu próxima acción.",
      silencio: "Durante dos turnos, nada de lo que hagas deja pista.",
      rastro: "Revela las pruebas físicas que hay en el escenario.",
      eco: "Revela las rutas que nadie mira.",
      presagio: "Te dice qué va a empeorar en el próximo turno, y cuánto.",
    },

    /* ── Los cinco tipos de pista ────────────────────────────────────────────────── */
    pistas: {
      testimonial: "Testimonial",
      fisica: "Física",
      temporal: "Temporal",
      digital: "Digital",
      intima: "Íntima",
    },
    pistasAyuda: {
      testimonial: "Alguien te vio, con o sin máscara.",
      fisica: "Un objeto: un jirón del traje, un guante quemado, una herramienta.",
      temporal: "Tu ausencia coincide con una aparición del héroe.",
      digital: "Una cámara, una foto de móvil, una publicación.",
      intima: "Las quemaduras en las manos, el insomnio, el olor a ozono, las mentiras torpes.",
    },
    pistaOrigen: {
      descargaIncendio: "Una descarga apagó el fuego antes que los bomberos.",
      "fragmento.manto": "Un jirón de tela quemada, enganchado y con tu olor encima.",
      "fragmento.guantes": "Un guante, con la palma reventada por dentro.",
      "fragmento.mascara": "Media máscara, en el suelo, junto a la salida.",
      "fragmento.botas": "Una suela con un dibujo que no es de este barrio.",
      "fragmento.torso": "Un trozo de tejido conductor, todavía tibio.",
      "fragmento.cinturon": "Una hebilla, y en la hebilla una inicial.",
      llaveAlmacen: "Una llave vieja, en el suelo del almacén, donde no debería estar.",
      manosQuemadas: "Traía las manos coloradas y no quiso decir por qué.",
      ausenciaTarde: "No estaba donde dijo que estaría.",
      camaraConcha: "La cámara del cruce lo cogió tres segundos.",
    },

    /* ── Expedientes ─────────────────────────────────────────────────────────────── */
    expediente: {
      titulo: "Expedientes",
      intro: "Cada persona lleva el suyo. No hay una barra de sospecha: hay gente.",
      pistasUna: "1 prueba",
      pistas: "{n} pruebas",
      faltaUna: "Le falta 1 para atar cabos",
      faltan: "Le faltan {n} para atar cabos",
      sinPistas: "Todavía no tiene nada.",
      interes: "Interés",
      umbral: "Umbral",
      sesgos: "Se fija en",
      estadoTitulo: "Estado",
      cerrado: "Lo sabe.",
      desenlaceAliado: "Aliado",
      desenlaceAmenaza: "Amenaza",
      desenlaceRuina: "Ruina",
      avisoObsesivo: "{quien} ha dejado de mirar hacia otro lado.",
      cerroExpediente: "{quien} lo sabe.",
      sinAvisos: "Este modo no te dice lo cerca que están.",
    },
    estados: {
      latente: "Latente",
      activo: "Activo",
      obsesivo: "Obsesivo",
      cerrado: "Cerrado",
    },
    estadosAyuda: {
      latente: "No investiga. Vive su vida.",
      activo: "Hace preguntas. Aparece donde no lo esperabas.",
      obsesivo: "Te sigue. Y necesita menos para estar seguro.",
      cerrado: "Ya no hace falta que investigue.",
    },

    /* ── El reparto ──────────────────────────────────────────────────────────────── */
    personajes: {
      dani: "Dani Vela",
      nuria: "Nuria Vela",
      carmen: "Carmen Ferrer",
      tomas: "Tomás Vela",
      isma: "Isma Doblas",
      julia: "Julia Reig",
      oscar: "Óscar Nieto",
      requena: "Emiliano Requena",
      pilar: "Doña Pilar",
      yusuf: "Yusuf Benali",
      sabater: "Inspectora Sabater",
      marga: "Marga Ossorio",
      ezequiel: "Ezequiel Reig",
      iria: "Dra. Iria Lem",
      tasador: "El Tasador",
      hierro: "Hierro",
      larga: "Larga",
      vigia: "La Vigía",
      cero: "Cero",
      chapa: "Chapa",
      tuerca: "Tuerca",
      sordo: "El Sordo",
    },
    personajesRol: {
      dani: "Quince años. Fiable, que es justo la virtud que esto destruye.",
      nuria: "Doce años. Tu hermana. Escribe. Se fija en todo y no dice nada hasta estar segura.",
      carmen: "Tu madre. Enfermera de urgencias. Turnos de noche.",
      tomas: "Tu padre. Técnico de mantenimiento en Eléctrica Marés.",
      isma: "Tu mejor amigo. Cómics, cámara y una carpeta llena de teorías.",
      julia: "De tu clase. Reservada, buena en física. Hija de Ezequiel Reig.",
      oscar: "El matón de clase. Su hermano está en Los Cabos.",
      requena: "Profesor de física. Cincuenta y ocho años y una culpa de veinte.",
      pilar: "La portera. No entiende de superhéroes: entiende de horarios.",
      yusuf: "Locutorio y taller en el Puerto Viejo. No pregunta.",
      sabater: "Unidad de Análisis. No es mala. Es buena en su trabajo.",
      marga: "Redactora de El Faro de Marés. Publicar te sube el Rango y te sube el cerco.",
      ezequiel: "Presidente de Eléctrica Marés. No quiere matarte: quiere patentarte.",
      iria: "Investigadora arrepentida. Tu fuente dentro de la empresa.",
      tasador: "Abre cajas fuertes sin tocarlas. Te va a enseñar que la fuerza no basta.",
      hierro: "Exboxeador con un exoesqueleto de obra. Pelea para pagar un tratamiento.",
      larga: "Tu contraparte exacta: tú iluminas, ella apaga.",
      vigia: "Otra elegida, hace nueve años. Hoy no tiene ni nombre.",
      cero: "Diseñó el proyecto y el cofre. Cree que quien tiene el poder debe renunciar a todo lo demás.",
      chapa: "Los Cabos. Puerto Viejo.",
      tuerca: "Los Cabos. Puerto Viejo.",
      sordo: "Los Cabos. Puerto Viejo.",
    },

    /* ── Las salas del instituto ─────────────────────────────────────
     * No son distritos —el distrito sigue siendo el instituto— pero sí son sitios con nombre:
     * el telón de `Transicion` necesita algo que poner en la cartela al cruzar la puerta.
     */
    salas: {
      aula: "Aula de 3.º B",
      pasillo: "Pasillo de planta",
      laboratorio: "Laboratorio de física",
      azotea: "La azotea",
    },
    salasAyuda: {
      aula: "Tercera hora. Requena, el encerado y veinte personas que no saben nada.",
      pasillo: "Taquillas, corcho y el sitio donde se entera todo el mundo de todo.",
      laboratorio: "El sitio del que alguien se llevó un cuaderno sin forzar la puerta.",
      azotea: "Se sube por la escalera de incendios y lo sabe medio tercero.",
    },
    /* ── Marés ───────────────────────────────────────────────────────────────────── */
    distritos: {
      aguas: "Barrio de las Aguas",
      instituto: "IES Miguel Servet",
      concha: "La Concha",
      puerto: "Puerto Viejo",
      financiero: "Distrito Financiero",
      faro: "Cerro del Faro",
      poligono: "Polígono Norte",
      hospital: "Hospital del Puerto",
      tolvas: "Las Tolvas",
    },
    distritosAyuda: {
      aguas: "Tu casa, el bloque, Doña Pilar. Cálido y estrecho.",
      instituto: "Clase, azotea, el laboratorio de Requena. La vida que arriesgas.",
      concha: "Comercios y plaza. Cámaras por todas partes.",
      puerto: "Muelles y almacenes. Sin cámaras. Territorio de Los Cabos.",
      financiero: "La torre de Eléctrica Marés. Vidrio, seguridad y altura.",
      faro: "Silencio y miradores. Aquí aparece La Vigía.",
      poligono: "La subestación y las naves. Donde todo empezó.",
      hospital: "El turno de tu madre. Donde llegan los que no salvaste.",
      tolvas: "Las ruinas de la antigua central. Prohibido.",
    },

    /* ── Bloques y acciones ──────────────────────────────────────────────────────── */
    bloques: { manana: "Mañana", tarde: "Tarde", noche: "Noche" },
    acciones: {
      obligacion: "Clase / familia",
      quedar: "Quedar con alguien",
      entrenar: "Entrenar",
      taller: "Taller",
      trabajar: "Trabajar",
      investigar: "Investigar",
      contramedidas: "Contramedidas",
      patrullar: "Patrullar",
      descansar: "Descansar",
      faltar: "Faltar",
    },
    accionesAyuda: {
      obligacion: "Mantiene los vínculos y evita las pistas Temporales.",
      quedar: "Sube el vínculo. A veces enseña algo.",
      entrenar: "Sube una estadística en el punto que elijas.",
      taller: "Construir o reparar el traje.",
      trabajar: "Repartos con Yusuf. Dinero.",
      investigar: "Tu propia investigación: quién dejó la llave.",
      contramedidas: "Retirar una prueba concreta de un expediente concreto.",
      patrullar: "Escaramuzas: experiencia, materiales y Rango. Y exposición.",
      descansar: "Recuperas Compostura y todo el mundo se enfría un poco.",
      faltar: "No ir. Tiene precio.",
    },
    bloqueNoDisponible: "Eso no se puede hacer por la {bloque}.",
    diaDe: "Día {dia} de {total}",
    capituloN: "Capítulo {n}",

    /* ── La Intervención ─────────────────────────────────────────────────────────── */
    intervencion: {
      titulo: "Intervención",
      escaramuza: "Escaramuza",
      decisiva: "Intervención decisiva",
      objetivo: "Objetivo",
      objetivosOpcionales: "Opcionales",
      reloj: "Reloj",
      turnoUno: "Queda 1 turno",
      turnos: "Quedan {n} turnos",
      testigos: "Testigos",
      sinTestigos: "Nadie mirando.",
      rutaVisible: "Por la calle — rápido y a la vista",
      rutaSombra: "Por las sombras — lento y limpio",
      vaAEmpeorar: "Si gastas otro turno: {que}",
      arrastraRuta: "Arrastra desde donde estás hasta donde quieres ir.",
      fuenteElectrica: "Hay corriente aquí. Un turno y la batería se llena.",
      salir: "Abandonar",
    },
    objetivos: {
      neutralizar: "Detener a quien está haciendo esto",
      rescatar: "Sacar a la gente de ahí",
      desactivar: "Cortarlo antes de que siga",
      recuperar: "Recuperar lo que dejaste",
    },
    agravamientos: {
      refuerzos: "llegan más",
      huida: "se acerca al coche",
      humo: "el humo baja una planta",
      desmayo: "el rehén deja de responder",
      propagacion: "el fuego sube",
      cortocircuito: "salta el cuadro",
      barridoPolicial: "la patrulla entra por el otro lado",
      lluvia: "empieza a llover sobre la prueba",
    },
    resultados: {
      impecable: "Impecable",
      limpio: "Limpio",
      sucio: "Sucio",
      parcial: "Parcial",
      fallido: "Fallido",
    },
    resultadosAyuda: {
      impecable: "Objetivo cumplido y nadie vio nada.",
      limpio: "Objetivo cumplido. Una sola prueba por ahí.",
      sucio: "Lo conseguiste. Y dejaste rastro.",
      parcial: "El principal se te escapó. Salvaste lo demás.",
      fallido: "Esta noche no. La historia sigue igualmente.",
    },

    /* ── El duelo ────────────────────────────────────────────────────────────────── */
    duelo: {
      titulo: "Duelo",
      basicas: "Básicas",
      tecnicasMenu: "Técnicas",
      entorno: "Entorno",
      contener: "Contener",
      contenerAyuda: "Resolverlo sin ganarlo. Cuesta turnos, no da experiencia y no deja nada.",
      golpear: "Golpear",
      esquivar: "Esquivar",
      agarrar: "Agarrar",
      retirarse: "Retirarse",
      visibilidad: "Visibilidad",
      visibilidadNula: "No te ve nadie",
      probabilidad: "{p}% de que salga",
      sinCarga: "Sin Carga",
      bloqueadaCompostura: "Necesitas concentración y no la tienes",
      agotada: "Ya la has usado",
      acierta: "Acierta.",
      falla: "Falla.",
      torpeza: "Y encima se te cae algo.",
      ganado: "Duelo resuelto.",
      contenido: "Contenido. Nadie sabrá que estuviste aquí.",
      caiste: "Se te acabó.",
      entornoAcciones: {
        tirarAndamio: "Tirar el andamio",
        cortarLuz: "Cortar la luz",
        abrirBocaRiego: "Abrir la boca de riego",
        volcarContenedor: "Volcar el contenedor",
        subirCatenaria: "Subir por la catenaria",
        cerrarCuadro: "Cerrar el cuadro",
      },
    },

    /* ── El traje ────────────────────────────────────────────────────────────────── */
    trajeUI: {
      titulo: "Traje",
      construir: "Construir",
      reparar: "Reparar",
      integridad: "Integridad",
      ocultacion: "Ocultación",
      materiales: "Materiales",
      cuesta: "Cuesta",
      yUnBloque: "y un bloque",
      sinMateriales: "No te llega.",
      reconocible: "Reconocible: te pueden describir.",
      dejaFragmentos: "Se está deshaciendo. Vas dejando trozos.",
      destruida: "Destruida. No aporta nada hasta que la rehagas.",
      generacionNueva: "Puedes montar el siguiente.",
      da: "Da",
      quita: "Cuesta",
    },
    ranuras: {
      mascara: "Máscara",
      torso: "Torso",
      guantes: "Guantes",
      botas: "Botas",
      cinturon: "Cinturón",
      manto: "Manto",
    },
    ranurasAyuda: {
      mascara: "Cuanto mejor tapa, peor ves.",
      torso: "El tejido conductor lleva carga — y brilla en la oscuridad.",
      guantes: "Los buenos conductores se calientan. Te queman las manos.",
      botas: "Las suelas rápidas son ruidosas.",
      cinturon: "Herramientas y cargas. Y peso.",
      manto: "Reduce daño y es lo primero que se rasga.",
    },
    generaciones: {
      improvisado: "Improvisado",
      taller: "De taller",
      aislado: "Aislado",
      conductor: "Conductor",
      fulgor: "Fulgor",
    },
    generacionesAyuda: {
      improvisado: "Una sudadera, un pañuelo y unos guantes de fregar.",
      taller: "Neopreno de segunda mano y cinta aislante. Funciona.",
      aislado: "Material de verdad, por fin.",
      conductor: "Mucho más poder. Y mucho menos escondido.",
      fulgor: "Lo hicisteis entre todos. Literalmente.",
    },
    materiales: {
      cobre: "Cobre recuperado",
      fibra: "Fibra",
      ceramica: "Cerámica",
      neodimio: "Imán de neodimio",
      optica: "Óptica",
      nucleo: "Núcleo",
    },

    /* ── Vínculos ────────────────────────────────────────────────────────────────── */
    vinculos: {
      titulo: "Vínculos",
      coartada: "Coartada",
      coartadaDe: "{quien} dirá que estabas con ella.",
      coartadaCuesta: "Te costará algo con {quien}.",
      coartadaGratis: "{quien} lo hará sin que se lo pidas. Ya lo sabe.",
      sinCoartadas: "No hay nadie lo bastante cerca.",
      confidente: "Confidente",
      confidentes: "Confidentes",
      favorUsado: "Ya se lo has pedido este capítulo.",
      ismaFalla: "A Isma le tiemblan las manos. Ha salido peor.",
      subeVinculo: "Estáis un poco más cerca.",
      bajaVinculo: "Se ha notado que no estabas.",
    },

    /* ── Dificultad ──────────────────────────────────────────────────────────────── */
    dificultades: {
      facil: "Leyenda urbana",
      medio: "Doble vida",
      dificil: "Sin máscara",
    },
    dificultadesAyuda: {
      facil: "Para quien viene por la historia. Marés casi disfruta del rumor y nadie tiene prisa por ponerle nombre.",
      medio: "El juego tal y como está pensado. Te miran lo justo y te perdonan lo justo.",
      dificil: "Marés quiere un nombre y lo quiere ya. No sabrás lo cerca que están hasta que pase.",
    },
    dificultadNota: "La dificultad mueve cuánto te miran y cuánto margen tienes. Nunca cuánto pegan los demás.",
    dificultadCambio: "Puedes cambiarla entre capítulos, en los dos sentidos, sin marca ninguna.",

    /* ── Guardado y transferencia ────────────────────────────────────────────────── */
    guardado: {
      titulo: "Guardado y transferencia",
      ranura: "Ranura {n}",
      ranuraVacia: "Vacía",
      guardarAhora: "Guardar ahora",
      guardada: "Partida guardada.",
      noSePudo: "Este navegador no ha podido guardar.",
      exportar: "Exportar",
      exportarAyuda: "Copia este código y pégalo en el otro dispositivo.",
      caracteres: "{n} caracteres",
      copiar: "Copiar",
      copiado: "Copiado.",
      copiarFallo: "Cópialo a mano: selecciona el texto y usa Ctrl+C.",
      importar: "Importar",
      importarAyuda: "Pega aquí el código de la otra partida.",
      importarSobre: "Importar sobre esta partida",
      importarEnLibre: "Importar en una ranura libre",
      importarConfirmar: "Esto sustituye la partida que tienes abierta. ¿Seguro?",
      codigoDanado: "El código está incompleto o dañado.",
      codigoDeOtroJuego: "Ese código no es de FULGOR.",
      codigoImportado: "Partida importada.",
      autoguardado: "Guardado automático",
    },

    /* ── Prensa ──────────────────────────────────────────────────────────────────── */
    prensa: {
      cabecera: "El Faro de Marés",
      favorable: "ALGUIEN LOS SACÓ A TIEMPO",
      neutra: "NUEVO INCIDENTE EN {distrito}",
      negativa: "DESTROZOS Y NINGUNA EXPLICACIÓN",
      firma: "Marga Ossorio",
      pieDeFoto: "La imagen es mala. La imagen siempre es mala.",
    },

    /* ── Informes de Sabater ─────────────────────────────────────────────────────── */
    informe: {
      cabecera: "UNIDAD DE ANÁLISIS · MARÉS",
      referencia: "Ref. {n}",
      apartadoPruebas: "ELEMENTOS OBRANTES",
      apartadoValoracion: "VALORACIÓN",
      valoracionBaja: "Sin elementos suficientes para orientar la investigación.",
      valoracionMedia: "Los indicios apuntan a un varón joven con residencia en la zona.",
      valoracionAlta: "Los elementos disponibles permiten acotar la identidad del sujeto.",
      pieDePagina: "Documento de trabajo. No difundir.",
    },

    /* ── Finales ─────────────────────────────────────────────────────────────────── */
    finales: {
      secretoIntacto: "El secreto intacto",
      laVigia: "La Vigía",
      aCaraDescubierta: "A cara descubierta",
      desenmascarado: "Desenmascarado",
      elRelevo: "El relevo",
      losDos: "Los dos",
      ciudadAOscuras: "La ciudad a oscuras",
    },
    finalesTexto: {
      secretoIntacto: "Nadie te descubrió salvo quien tú elegiste. El lunes vuelves a clase, y eso es exactamente lo que querías.",
      laVigia: "Salvaste la ciudad y no te quedó nadie. Es el mismo final que Noor, y el juego no va a fingir que no lo es.",
      aCaraDescubierta: "Te la quitaste tú. Ganaste el combate y perdiste la vida que llevabas ocho horas protegiendo.",
      desenmascarado: "Sabater cerró el expediente. Hizo bien su trabajo y tú hiciste lo que pudiste.",
      elRelevo: "Le pasaste la llave a otro, como Sesé quería. Pero en tus términos.",
      losDos: "La doble vida se sostiene porque hay gente sosteniéndola contigo. Sesé se equivocaba.",
      ciudadAOscuras: "Marés sobrevive. Tú también. Nada vuelve a ser igual.",
    },

    /* ── Pistas de control (catálogo) ────────────────────────────────────────────── */
    controles: "Empieza con un prólogo de cinco cartas que te cuenta quién eres, quién te mira y qué se te pide; se puede saltar. La pantalla está partida en dos: arriba se ve Marés y abajo se decide. Se anda con la cruceta o con las flechas y se habla con el botón A o con el espacio, que es también lo que avanza el texto —el primer toque completa la frase y el segundo pasa a la siguiente—. No hay menú de acciones: las nueve cosas que puedes hacer con un bloque del día son gente y sitios de la ciudad, así que hablar con tu hermana en la plaza ES quedar con ella, y hacerlo gasta la tarde. El día tiene tres bloques y una emergencia puede sonar en cualquiera. En una Intervención caminas el mismo distrito de noche, con los testigos de pie y sus conos de luz en el suelo, y el reloj de arriba no cuenta tu fracaso: dice qué va a empeorar en el turno siguiente. En un duelo cada técnica enseña su coste de Carga y sus puntitos de visibilidad ANTES de elegirla, y Contener cierra el combate sin ganarlo y sin dejar una prueba. Los iconos de arriba a la derecha abren el mapa, los expedientes, el traje y el guardado, desde donde exportas un código para seguir la partida en otro dispositivo. Se guarda solo.",

    /* ── La historia ─────────────────────────────────────────────────────────────── */
    capitulos: {
      c1: "La llave",
      c2: "Primeras chispas",
      c3: "El Tasador",
      c4: "Coartadas",
      c5: "Hierro",
      c6: "El faro",
      c7: "El Faro de Marés",
      c8: "Lo que Isma sabía",
      c9: "Eléctrica Marés",
      c10: "El apagón",
      c11: "Cero",
      c12: "El nombre",
    },
    capitulosIntro: {
      c1: "Un día entero de instituto, casa y examen de Requena. La vida de antes, para que sepas qué estás a punto de arriesgar.",
      c2: "Tres días aprendiendo a no romper cosas. Las bombillas, el móvil de Nuria, la nevera. Y un incendio en un bajo de las Aguas.",
      c3: "Marés tiene un ladrón que abre cajas fuertes sin tocarlas. Se abre el Puerto Viejo, y con él Yusuf.",
      c4: "Sabater llega a Marés y pasa por el instituto. A partir de hoy hay expedientes, y a partir de hoy se pueden vaciar.",
      c5: "Un hombre con un exoesqueleto está reventando cajeros. Y es el cumpleaños de Nuria.",
      c6: "Alguien te ha estado siguiendo. Sube al Cerro del Faro.",
      c7: "Marga te ofrece un trato: cuéntame algo y controlo la narrativa.",
      c8: "Isma lo sabe. La única variable es cómo se entera.",
      c9: "La torre del Distrito Financiero, por dentro. Y la firma de tu padre debajo de todo.",
      c10: "Marés entera se queda a oscuras. Ocho horas. Tu poder es lo único que funciona.",
      c11: "Las Tolvas. Sesé, el cofre y las cuatro generaciones que hubo antes que tú.",
      c12: "Reig ha activado la central. Otra vez todo el mundo mirando.",
    },
    /* ── El prólogo jugable (§11.6) ───────────────────────────────────────
     * Antes de la primera escena, el juego dice de qué va, quién es quién y qué se le pide
     * al jugador. Cinco cartas y ninguna obligatoria: se pueden saltar de una en una.
     */
    prologo: {
      titulo: "Antes de empezar",
      saltar: "Saltar la introducción",
      siguiente: "Seguir",
      empezar: "Empezar el capítulo 1",
      paso: "{n} de {total}",

      queEsTitulo: "Qué es esto",
      queEsUno: "Tienes quince años, te llamas Dani Vela y vives en Marés.",
      queEsDos: "Una noche te cae encima el rayo. Desde entonces tienes dos vidas que no pueden tocarse.",
      queEsTres: "No va de ganar peleas: va de volver a casa sin que nadie sepa dónde estuviste.",

      quienTitulo: "Quién es quién",
      quienUno: "Trece personas te miran, y cada una se fija en algo distinto.",
      quienDos: "Nuria nota los aparatos que se funden. Requena te mira las manos. Doña Pilar sabe a qué hora vuelves.",
      quienTres: "Y Sabater no se fija en nada de eso. Se fija en tus horarios.",

      objetivoTitulo: "Qué se te pide",
      objetivoUno: "El secreto no es una barra: son trece expedientes, uno por persona.",
      objetivoDos: "Salvar a alguien los llena. Fallarle a alguien los vacía. No hay jugada que haga las dos.",
      objetivoTres: "Doce capítulos y siete finales. Ninguno es el bueno.",

      dosVidasTitulo: "Las dos mitades del día",
      dosVidasUno: "El día tiene tres bloques: mañana, tarde y noche. Hablar con alguien gasta uno.",
      dosVidasDos: "Por eso no hay menú. Nuria está sentada en la plaza, y para irte tienes que cruzarla.",
      dosVidasTres: "Y cuando suena un aviso, la ciudad no espera a que acabes.",

      controlesTitulo: "Cómo se juega",
      controlesUno: "Arriba se ve Marés, abajo se decide. Cruceta o flechas para andar; A o espacio para hablar.",
      controlesDos: "En una Intervención, el reloj no cuenta tu fracaso: cuenta qué va a empeorar.",
      controlesTres: "Se guarda solo. Y esto se puede releer desde el menú de pausa.",
    },

    /* ── La apertura animada ───────────────────────────────────────────────
     * Ocho frases sobre negro entre el prólogo y el primer bloque jugable. No explican nada
     * —eso ya lo ha hecho el prólogo—: ponen el tono y prometen la pregunta del capítulo 12.
     */
    apertura: {
      f1: "Marés tiene ciento diez mil habitantes",
      f2: "y una central que lleva cuarenta años apagada.",
      f3: "Hace veinte años, alguien eligió a cuatro chicos.",
      f4: "De tres se sabe lo que pasó.",
      f5: "Esta noche hay una llave en el suelo de un portal",
      f6: "y un papel doblado debajo.",
      f7: "Puedes recogerla o dejarla donde está.",
      f8: "Nadie va a preguntarte nunca por qué la recogiste.",
      pulsa: "Toca para seguir",
    },
  },

  en: {
    /* ── Identity ────────────────────────────────────────────────────────────────── */
    meta: {
      titulo: "FULGOR",
      lema: "You're fifteen, you've got the lightning, and you've got two lives that must never touch.",
      subtitulo: "Marés · a double-life action RPG",
      autoria: "A game about keeping a lie standing.",
    },

    ui: {
      empezar: "Start",
      partidaNueva: "New game",
      continuar: "Continue",
      importarCodigo: "Import code",
      volver: "Back",
      cerrar: "Close",
      aceptar: "OK",
      cancelar: "Cancel",
      siguiente: "Next",
      confirmar: "Confirm",
      guardar: "Save",
      opciones: "Options",
      creditos: "Credits",
      pausa: "Pause",
      saltar: "Skip",
      idioma: "Language",
      dificultad: "Difficulty",
      expedientes: "Files",
      traje: "Suit",
      tecnicas: "Techniques",
      mapa: "Map",
      diario: "Journal",
      sinDatos: "Nothing here yet.",
      cargando: "Loading…",

      /* The walkable world: the lower screen no longer offers actions, it informs and drives. */
      capitulo: "Chapter",
      dia: "Day",
      mover: "Move",
      hablar: "Talk",
      entrar: "Enter",
      nadaCerca: "Nothing nearby",
      seHaceDeNoche: "The day is ending",
    },

    recursos: {
      carga: "Charge",
      compostura: "Composure",
      cargaAyuda: "The battery. Every technique spends it; touching live current fills it.",
      composturaAyuda: "Body and nerve. As it drops you don't just miss — you get seen.",
      rango: "Standing",
      rangoAyuda: "What Marés thinks it knows about you. It rises with you — and Sabater rises with it.",
      dinero: "Money",
      nivel: "Level",
      xp: "Experience",
      puntosLibres: "Points to spend",
    },
    stats: {
      potencia: "Power",
      cuerpo: "Body",
      control: "Control",
      guardia: "Guard",
      velocidad: "Speed",
      aguante: "Stamina",
      temple: "Nerve",
    },
    statsAyuda: {
      potencia: "Damage from Impact techniques.",
      cuerpo: "Breaking holds, shoving, taking hits.",
      control: "Precision: landing it without wrecking the street.",
      guardia: "Cuts damage taken and wear on the suit.",
      velocidad: "Turn cost of routes, and initiative in a duel.",
      aguante: "Maximum Charge and how fast it comes back.",
      temple: "Maximum Composure; resistance to fear and pain.",
    },

    afinidades: { rayo: "Bolt", luz: "Light", sombra: "Shadow", materia: "Matter" },
    afinidadesAyuda: {
      rayo: "Raw electrical force: impact, stun, overload.",
      luz: "Perception: blind, illuminate, reveal. The opposite of hiding.",
      sombra: "Concealment, silence, switching things off. Almost invisible.",
      materia: "The physical and the mechanical: metal, structures, machines.",
    },
    afinidadVentaja: "{atacante} has the edge over {defensor}.",
    afinidadDesventaja: "{atacante} is up against it with {defensor}.",

    familias: {
      impacto: "Impact",
      velocidad: "Speed",
      luz: "Light",
      escudo: "Shield",
      sentido: "Sense",
    },
    familiasAyuda: {
      impacto: "Settle a duel by force.",
      velocidad: "Move free, take initiative, get out.",
      luz: "Blind, reveal, see through, distract.",
      escudo: "Absorb, cover a civilian, hold on.",
      sentido: "Does no damage. Buys information, which is what is actually won here.",
    },

    /* Hissatsu names: approved on how they sound shouted, never on how literal they are. */
    tecnicas: {
      chispazo: "Jolt",
      arcoVoltaico: "Arc Flash",
      punoTormenta: "Thunderfist",
      yunque: "Anvil Drop",
      sobrecarga: "Overload",
      truenoSeco: "Thunderclap",
      martillo: "Sledge",
      chispaFria: "Coldspark",
      descargaCero: "Nullbolt",
      pasoCorto: "Blink Step",
      relampago: "Streak",
      vaho: "Blackout Step",
      fuga: "Vanish",
      estela: "Slipstream",
      cortocircuito: "Shortout",
      sombraLarga: "Longshadow",
      destello: "Whiteout",
      espejismo: "Mirage",
      prisma: "Prism",
      fulgor: "Blaze",
      cortina: "Nightfall",
      aurora: "Aurora",
      reflejo: "Mirrorback",
      alba: "Daybreak",
      pararrayos: "Lightning Rod",
      malla: "Meshguard",
      aguanteTec: "Second Wind",
      jaula: "Cage",
      tierra: "Deadearth",
      cupula: "Dome",
      ancla: "Anchor",
      escucha: "Earshot",
      lectura: "Tell",
      barrido: "Sweep",
      pulso: "Pulse",
      anticipo: "Edge",
      silencio: "Hush",
      rastro: "Trace",
      eco: "Echo",
      presagio: "Omen",
    },
    tecnicasAyuda: {
      chispazo: "Low damage, never lets you down. The first thing you learned to do on purpose.",
      arcoVoltaico: "Big damage, catches two. Visible from the far pavement.",
      punoTormenta: "If it lands, the duel is over. And everyone will know you were there.",
      yunque: "Brings down whatever the node is holding up.",
      sobrecarga: "Kills any device with current in it.",
      truenoSeco: "Short, dry, no flourish. Hierro taught you that counts too.",
      martillo: "Ignores the guard. No stance survives this.",
      chispaFria: "Light that hits without burning: it hurts and it barely shows.",
      descargaCero: "Everything you have, all at once, and quietly.",
      pasoCorto: "One node, no turn spent.",
      relampago: "Half the map instantly. And a line of light pointing at where you went.",
      vaho: "Breaks the duel and leaves nothing behind.",
      fuga: "You get out — and take a Testimony clue with you.",
      estela: "You take next turn's initiative.",
      cortocircuito: "Kills the power across the whole node.",
      sombraLarga: "You cross the map by the places with no light to draw you.",
      destello: "Blinds: the opponent loses a turn. The whole street sees it too.",
      espejismo: "Witnesses see someone else. None of them lies when they give a statement.",
      prisma: "Splits one attack across three opponents.",
      fulgor: "Settles every duel in the node. And makes every camera.",
      cortina: "Kills every light in the node.",
      aurora: "A sheet of light that sweeps two of them off.",
      reflejo: "Sends the next attack back the way it came.",
      alba: "Reveals all of it: cameras, witnesses, exits, routes.",
      pararrayos: "Absorbs the next attack and turns it into Charge.",
      malla: "Covers a civilian for two turns.",
      aguanteTec: "Composure back. Breathing is a technique too.",
      jaula: "Holds without hurting. Containing, but properly.",
      tierra: "Cancels the opponent's affinity edge.",
      cupula: "Covers the whole node for a turn.",
      ancla: "No hold is shifting you.",
      escucha: "Shows who is waiting in the neighbouring nodes.",
      lectura: "Shows what the opponent will do next turn.",
      barrido: "Marks every camera and every witness on the map.",
      pulso: "Shows the full layout, hidden routes included.",
      anticipo: "+25% on your next action.",
      silencio: "For two turns, nothing you do leaves a trace.",
      rastro: "Shows the physical evidence lying around.",
      eco: "Shows the routes nobody is watching.",
      presagio: "Tells you what gets worse next turn, and by how much.",
    },

    pistas: {
      testimonial: "Testimony",
      fisica: "Physical",
      temporal: "Timing",
      digital: "Digital",
      intima: "Intimate",
    },
    pistasAyuda: {
      testimonial: "Someone saw you, masked or not.",
      fisica: "An object: a strip of the suit, a burnt glove, a tool.",
      temporal: "Where you weren't lines up with where he was.",
      digital: "A camera, a phone photo, a post.",
      intima: "Burnt hands, no sleep, the smell of ozone, clumsy lies.",
    },
    pistaOrigen: {
      descargaIncendio: "Something put the fire out before the brigade got there.",
      "fragmento.manto": "A strip of scorched cloth, snagged, and it smells of you.",
      "fragmento.guantes": "A glove, blown out from the inside.",
      "fragmento.mascara": "Half a mask, on the floor, by the way out.",
      "fragmento.botas": "A sole with a tread nobody round here wears.",
      "fragmento.torso": "A piece of conductive weave, still warm.",
      "fragmento.cinturon": "A buckle. And an initial on the buckle.",
      llaveAlmacen: "An old key, on the warehouse floor, where no key should be.",
      manosQuemadas: "His hands were red raw and he wouldn't say why.",
      ausenciaTarde: "He wasn't where he said he'd be.",
      camaraConcha: "The junction camera caught him for three seconds.",
    },

    expediente: {
      titulo: "Files",
      intro: "Everyone keeps their own. There is no suspicion bar: there are people.",
      pistasUna: "1 piece",
      pistas: "{n} pieces",
      faltaUna: "1 more and it adds up",
      faltan: "{n} more and it adds up",
      sinPistas: "Nothing yet.",
      interes: "Attention",
      umbral: "Threshold",
      sesgos: "Notices",
      estadoTitulo: "State",
      cerrado: "They know.",
      desenlaceAliado: "Ally",
      desenlaceAmenaza: "Threat",
      desenlaceRuina: "Ruin",
      avisoObsesivo: "{quien} has stopped looking the other way.",
      cerroExpediente: "{quien} knows.",
      sinAvisos: "This mode won't tell you how close they are.",
    },
    estados: {
      latente: "Dormant",
      activo: "Active",
      obsesivo: "Fixated",
      cerrado: "Closed",
    },
    estadosAyuda: {
      latente: "Not looking. Getting on with life.",
      activo: "Asking questions. Turning up where you didn't expect.",
      obsesivo: "Following you. And needing less to be sure.",
      cerrado: "No longer needs to look.",
    },

    personajes: {
      dani: "Dani Vela",
      nuria: "Nuria Vela",
      carmen: "Carmen Ferrer",
      tomas: "Tomás Vela",
      isma: "Isma Doblas",
      julia: "Julia Reig",
      oscar: "Óscar Nieto",
      requena: "Emiliano Requena",
      pilar: "Doña Pilar",
      yusuf: "Yusuf Benali",
      sabater: "Inspector Sabater",
      marga: "Marga Ossorio",
      ezequiel: "Ezequiel Reig",
      iria: "Dr Iria Lem",
      tasador: "El Tasador",
      hierro: "Hierro",
      larga: "Larga",
      vigia: "La Vigía",
      cero: "Cero",
      chapa: "Chapa",
      tuerca: "Tuerca",
      sordo: "El Sordo",
    },
    personajesRol: {
      dani: "Fifteen. Reliable — which is exactly the virtue this destroys.",
      nuria: "Twelve. Your sister. She writes. She notices everything and says nothing until she's sure.",
      carmen: "Your mother. A&E nurse. Night shifts.",
      tomas: "Your father. Maintenance technician at Eléctrica Marés.",
      isma: "Your best friend. Comics, a camera, and a folder full of theories.",
      julia: "In your class. Quiet, good at physics. Ezequiel Reig's daughter.",
      oscar: "The one who shoves you in the corridor. His brother runs with Los Cabos.",
      requena: "Physics teacher. Fifty-eight years old and twenty years of guilt.",
      pilar: "The concierge — everyone calls her Doña Pilar and nobody calls her Pilar. She doesn't understand superheroes. She understands what time people come home.",
      yusuf: "Phone shop and workshop in Puerto Viejo. Doesn't ask.",
      sabater: "Analysis Unit. She isn't the villain. She's good at her job.",
      marga: "Writes for El Faro de Marés. Getting printed raises your standing and tightens the net.",
      ezequiel: "Chairman of Eléctrica Marés. He doesn't want you dead: he wants you patented.",
      iria: "A researcher who regrets it. Your source inside the company.",
      tasador: "Opens safes without touching them. He'll teach you force isn't enough.",
      hierro: "Ex-boxer in a construction exoskeleton. He fights to pay for treatment.",
      larga: "Your exact counterpart: you light things up, she puts them out.",
      vigia: "Another chosen one, nine years ago. Today she doesn't even have a name.",
      cero: "He designed the project and the chest. He believes whoever holds the power must give up everything else.",
      chapa: "Los Cabos. Puerto Viejo.",
      tuerca: "Los Cabos. Puerto Viejo.",
      sordo: "Los Cabos. Puerto Viejo.",
    },

    /* ── The rooms inside the school ───────────────────────────────── */
    salas: {
      aula: "Year 10 classroom",
      pasillo: "Upstairs corridor",
      laboratorio: "Physics lab",
      azotea: "The roof",
    },
    salasAyuda: {
      aula: "Third period. Requena, the blackboard and twenty people who know nothing.",
      pasillo: "Lockers, a noticeboard, and where everybody finds out everything.",
      laboratorio: "Where somebody took a notebook without forcing the door.",
      azotea: "Up the fire escape, and half the year knows it.",
    },
    distritos: {
      aguas: "Barrio de las Aguas",
      instituto: "IES Miguel Servet",
      concha: "La Concha",
      puerto: "Puerto Viejo",
      financiero: "The Financial District",
      faro: "Cerro del Faro",
      poligono: "Polígono Norte",
      hospital: "Hospital del Puerto",
      tolvas: "Las Tolvas",
    },
    distritosAyuda: {
      aguas: "Your flat, your block, Doña Pilar. Warm and narrow.",
      instituto: "Your school — classroom, roof, Requena's lab. The life you're risking.",
      concha: "Shops and the square. Cameras on every corner.",
      puerto: "The old docks and warehouses. No cameras. Los Cabos country.",
      financiero: "The Eléctrica Marés tower. Glass, security and height.",
      faro: "The lighthouse hill. Quiet, and a long view. This is where La Vigía turns up.",
      poligono: "The substation and the units. Where all this started.",
      hospital: "Your mother's shift. Where the ones you didn't save end up.",
      tolvas: "The ruins of the old power station. Off limits.",
    },

    bloques: { manana: "Morning", tarde: "Afternoon", noche: "Night" },
    acciones: {
      obligacion: "School / family",
      quedar: "See someone",
      entrenar: "Train",
      taller: "Workshop",
      trabajar: "Work",
      investigar: "Dig",
      contramedidas: "Countermeasures",
      patrullar: "Patrol",
      descansar: "Rest",
      faltar: "Skip it",
    },
    accionesAyuda: {
      obligacion: "Keeps the bonds warm and keeps Timing clues off the board.",
      quedar: "Raises the bond. Sometimes teaches you something.",
      entrenar: "Raises one stat at the spot you pick.",
      taller: "Build or repair the suit.",
      trabajar: "Deliveries for Yusuf. Money.",
      investigar: "Your own investigation: who left the key.",
      contramedidas: "Lift one specific piece of evidence out of one specific file.",
      patrullar: "Skirmishes: experience, materials and standing. And exposure.",
      descansar: "Composure back, and everybody cools off a little.",
      faltar: "Don't go. It costs.",
    },
    bloqueNoDisponible: "You can't do that in the {bloque}.",
    diaDe: "Day {dia} of {total}",
    capituloN: "Chapter {n}",

    intervencion: {
      titulo: "Intervention",
      escaramuza: "Skirmish",
      decisiva: "Decisive intervention",
      objetivo: "Objective",
      objetivosOpcionales: "Optional",
      reloj: "Clock",
      turnoUno: "1 turn left",
      turnos: "{n} turns left",
      testigos: "Witnesses",
      sinTestigos: "Nobody watching.",
      rutaVisible: "Street level — fast and out in the open",
      rutaSombra: "The dark way — slow and clean",
      vaAEmpeorar: "Spend another turn and: {que}",
      arrastraRuta: "Drag from where you are to where you want to be.",
      fuenteElectrica: "There's current here. One turn and the battery is full.",
      salir: "Walk away",
    },
    objetivos: {
      neutralizar: "Stop whoever is doing this",
      rescatar: "Get them out of there",
      desactivar: "Kill it before it spreads",
      recuperar: "Get back what you left behind",
    },
    agravamientos: {
      refuerzos: "more of them arrive",
      huida: "he reaches the car",
      humo: "the smoke drops a floor",
      desmayo: "the hostage stops answering",
      propagacion: "the fire climbs",
      cortocircuito: "the box blows",
      barridoPolicial: "the patrol comes in the other side",
      lluvia: "it starts raining on the evidence",
    },
    resultados: {
      impecable: "Spotless",
      limpio: "Clean",
      sucio: "Messy",
      parcial: "Partial",
      fallido: "Failed",
    },
    resultadosAyuda: {
      impecable: "Objective done and nobody saw a thing.",
      limpio: "Objective done. One loose end out there.",
      sucio: "You got it. And you left a trail.",
      parcial: "The main one got away. You saved the rest.",
      fallido: "Not tonight. The story carries on regardless.",
    },

    duelo: {
      titulo: "Duel",
      basicas: "Basic",
      tecnicasMenu: "Techniques",
      entorno: "Surroundings",
      contener: "Contain",
      contenerAyuda: "Settle it without winning it. Costs turns, earns nothing, leaves nothing.",
      golpear: "Strike",
      esquivar: "Dodge",
      agarrar: "Grapple",
      retirarse: "Pull back",
      visibilidad: "Visibility",
      visibilidadNula: "Nobody sees this",
      probabilidad: "{p}% it lands",
      sinCarga: "No Charge",
      bloqueadaCompostura: "This needs focus and you haven't got any",
      agotada: "Already used",
      acierta: "It lands.",
      falla: "It misses.",
      torpeza: "And you drop something.",
      ganado: "Duel settled.",
      contenido: "Contained. Nobody will know you were here.",
      caiste: "That's it. You're done.",
      entornoAcciones: {
        tirarAndamio: "Bring the scaffold down",
        cortarLuz: "Kill the lights",
        abrirBocaRiego: "Open the hydrant",
        volcarContenedor: "Tip the skip",
        subirCatenaria: "Go up the catenary",
        cerrarCuadro: "Trip the board",
      },
    },

    trajeUI: {
      titulo: "Suit",
      construir: "Build",
      reparar: "Repair",
      integridad: "Integrity",
      ocultacion: "Concealment",
      materiales: "Materials",
      cuesta: "Costs",
      yUnBloque: "and a block",
      sinMateriales: "Not enough.",
      reconocible: "Recognisable: they can describe this.",
      dejaFragmentos: "Coming apart. You're leaving pieces of it around.",
      destruida: "Destroyed. Gives you nothing until you rebuild it.",
      generacionNueva: "You can build the next one.",
      da: "Gives",
      quita: "Costs",
    },
    ranuras: {
      mascara: "Mask",
      torso: "Torso",
      guantes: "Gloves",
      botas: "Boots",
      cinturon: "Belt",
      manto: "Cloak",
    },
    ranurasAyuda: {
      mascara: "The better it hides you, the worse you see.",
      torso: "Conductive weave carries charge — and glows in the dark.",
      guantes: "Good conductors run hot. They burn your hands.",
      botas: "Fast soles are loud soles.",
      cinturon: "Tools and cells. And weight.",
      manto: "Cuts damage, and it's the first thing to tear.",
    },
    generaciones: {
      improvisado: "Improvised",
      taller: "Workshop",
      aislado: "Insulated",
      conductor: "Conductive",
      fulgor: "Fulgor",
    },
    generacionesAyuda: {
      improvisado: "A hoodie, a scarf and a pair of washing-up gloves.",
      taller: "Second-hand neoprene and electrical tape. It works.",
      aislado: "Real materials, finally.",
      conductor: "Far more power. And far less hidden.",
      fulgor: "You built it between you. Literally.",
    },
    materiales: {
      cobre: "Salvaged copper",
      fibra: "Fibre",
      ceramica: "Ceramic",
      neodimio: "Neodymium magnet",
      optica: "Optics",
      nucleo: "Core",
    },

    vinculos: {
      titulo: "Bonds",
      coartada: "Alibi",
      coartadaDe: "{quien} will say you were with her.",
      coartadaCuesta: "It'll cost you something with {quien}.",
      coartadaGratis: "{quien} will do it before you ask. She already knows.",
      sinCoartadas: "Nobody close enough.",
      confidente: "Confidant",
      confidentes: "Confidants",
      favorUsado: "You've already asked this chapter.",
      ismaFalla: "Isma's hands are shaking. It's come out worse.",
      subeVinculo: "You're a little closer.",
      bajaVinculo: "They noticed you weren't there.",
    },

    dificultades: {
      facil: "Urban Legend",
      medio: "Double Life",
      dificil: "No Mask",
    },
    dificultadesAyuda: {
      facil: "For anyone here for the story. Marés half enjoys the rumour and nobody's in a hurry to put a name to it.",
      medio: "The game as designed. They look at you just enough and forgive you just enough.",
      dificil: "Marés wants a name and wants it now. You won't know how close they are until it happens.",
    },
    dificultadNota: "Difficulty moves how hard they look at you and how much room you get. Never how hard anyone hits.",
    dificultadCambio: "You can change it between chapters, either way, with no mark against you.",

    guardado: {
      titulo: "Save and transfer",
      ranura: "Slot {n}",
      ranuraVacia: "Empty",
      guardarAhora: "Save now",
      guardada: "Game saved.",
      noSePudo: "This browser couldn't save.",
      exportar: "Export",
      exportarAyuda: "Copy this code and paste it on the other device.",
      caracteres: "{n} characters",
      copiar: "Copy",
      copiado: "Copied.",
      copiarFallo: "Copy it by hand: select the text and press Ctrl+C.",
      importar: "Import",
      importarAyuda: "Paste the code from the other game here.",
      importarSobre: "Import over this game",
      importarEnLibre: "Import into a free slot",
      importarConfirmar: "This replaces the game you have open. Are you sure?",
      codigoDanado: "The code is incomplete or damaged.",
      codigoDeOtroJuego: "That code isn't a FULGOR code.",
      codigoImportado: "Game imported.",
      autoguardado: "Autosaved",
    },

    /* Headline grammar, not translation: no articles, verb in the present (§13.2). */
    prensa: {
      cabecera: "The Marés Beacon",
      favorable: "SOMEONE GOT THEM OUT IN TIME",
      neutra: "FRESH INCIDENT IN {distrito}",
      negativa: "WRECKAGE, AND NO EXPLANATION",
      firma: "Marga Ossorio",
      pieDeFoto: "The picture is bad. The picture is always bad.",
    },

    /* Written again in real English police register, not carried over from the Spanish. */
    informe: {
      cabecera: "ANALYSIS UNIT · MARÉS",
      referencia: "Ref. {n}",
      apartadoPruebas: "MATERIAL HELD",
      apartadoValoracion: "ASSESSMENT",
      valoracionBaja: "Insufficient material to direct further enquiry.",
      valoracionMedia: "Indications point to a young male resident in the area.",
      valoracionAlta: "Material held is sufficient to narrow the subject's identity.",
      pieDePagina: "Working document. Not for circulation.",
    },

    finales: {
      secretoIntacto: "The Secret Held",
      laVigia: "La Vigía",
      aCaraDescubierta: "Bare-Faced",
      desenmascarado: "Unmasked",
      elRelevo: "The Handover",
      losDos: "Both",
      ciudadAOscuras: "The City in the Dark",
    },
    finalesTexto: {
      secretoIntacto: "Nobody found you out but the one you chose. On Monday you go back to school, and that is exactly what you wanted.",
      laVigia: "You saved the city and there was nobody left. It is the same ending Noor got, and the game isn't going to pretend otherwise.",
      aCaraDescubierta: "You took it off yourself. You won the fight and lost the life you'd spent eight hours protecting.",
      desenmascarado: "Sabater closed the file. She did her job well, and you did what you could.",
      elRelevo: "You handed the key on, the way Sesé wanted. On your terms, though.",
      losDos: "The double life stands up because there are people holding it up with you. Sesé had it wrong.",
      ciudadAOscuras: "Marés survives. So do you. Nothing goes back to how it was.",
    },

    controles: "It opens with a five-card prologue telling you who you are, who is watching and what is being asked of you; it can be skipped. The screen is split in two: Marés on top, decisions underneath. Walk with the d-pad or the arrow keys and talk with A or space, which also advances text — the first press completes the line, the second moves on. There is no action menu: the nine things you can spend a block of the day on are people and places in the city, so talking to your sister in the square IS seeing her, and it costs you the afternoon. A day has three blocks and an emergency can go off in any of them. In an Intervention you walk the same district at night, with the witnesses standing there and their cones of light on the ground, and the clock at the top doesn't count your failure: it says what gets worse next turn. In a duel every technique shows its Charge cost and its visibility dots BEFORE you commit, and Contain settles a fight without winning it and without leaving a trace. The icons top right open the map, the files, the suit and the save dialog, where you export a code to carry the game to another device. It saves itself.",

    capitulos: {
      c1: "The Key",
      c2: "First Sparks",
      c3: "El Tasador",
      c4: "Alibis",
      c5: "Hierro",
      c6: "The Lighthouse",
      c7: "The Marés Beacon",
      c8: "What Isma Knew",
      c9: "Eléctrica Marés",
      c10: "The Blackout",
      c11: "Cero",
      c12: "The Name",
    },
    capitulosIntro: {
      c1: "A whole day of school, home, and one of Requena's tests. The life from before, so you know what you're about to risk.",
      c2: "Three days learning not to break things. The bulbs, Nuria's phone, the fridge. And a fire in a ground-floor flat in Las Aguas.",
      c3: "Marés has a thief who opens safes without touching them. Puerto Viejo opens up, and Yusuf with it.",
      c4: "Sabater arrives in Marés and stops by the school. From today there are files — and from today they can be emptied.",
      c5: "A man in an exoskeleton is tearing cash machines out of walls. And it's Nuria's birthday.",
      c6: "Someone has been following you. Go up to Cerro del Faro.",
      c7: "Marga offers you a deal: give me something and I'll steer the story.",
      c8: "Isma knows. The only variable is how he finds out.",
      c9: "The Financial District tower, from the inside. And your father's signature under all of it.",
      c10: "The whole of Marés goes dark. Eight hours. Your power is the only thing still working.",
      c11: "Las Tolvas. Sesé, the chest, and the four generations there were before you.",
      c12: "Reig has fired up the station. Everybody watching again.",
    },
    /* ── The playable prologue (§11.6) ─────────────────────────────────── */
    prologo: {
      titulo: "Before you start",
      saltar: "Skip the introduction",
      siguiente: "Next",
      empezar: "Begin chapter 1",
      paso: "{n} of {total}",

      queEsTitulo: "What this is",
      queEsUno: "You are fifteen, your name is Dani Vela, and you live in Marés.",
      queEsDos: "One night the lightning finds you. After that you have two lives that cannot touch.",
      queEsTres: "It isn't about winning fights: it's about getting home unnoticed.",

      quienTitulo: "Who's who",
      quienUno: "Thirteen people are watching, and each notices something different.",
      quienDos: "Nuria notices devices dying. Requena looks at your hands. Doña Pilar knows your hours.",
      quienTres: "And Sabater notices none of that. She notices your timetable.",

      objetivoTitulo: "What's asked of you",
      objetivoUno: "The secret isn't a meter: it's thirteen files, one per person.",
      objetivoDos: "Saving someone fills them. Failing someone empties them. No move does both.",
      objetivoTres: "Twelve chapters and seven endings. None of them is the good one.",

      dosVidasTitulo: "The two halves of a day",
      dosVidasUno: "A day has three blocks: morning, afternoon, night. Talking to someone spends one.",
      dosVidasDos: "That's why there's no menu. Nuria is sitting in the square, and leaving means crossing it.",
      dosVidasTres: "And when a call comes in, the city doesn't wait for you to finish.",

      controlesTitulo: "How it plays",
      controlesUno: "Marés on top, decisions below. D-pad or arrows to walk; A or space to talk.",
      controlesDos: "In an Intervention the clock doesn't count failure: it counts what gets worse.",
      controlesTres: "It saves itself. And this can be read again from the pause menu.",
    },

    /* ── The animated opening ──────────────────────────────────────── */
    apertura: {
      f1: "Marés has a hundred and ten thousand people",
      f2: "and a power station forty years dark.",
      f3: "Twenty years ago, somebody chose four children.",
      f4: "Three of them, we know what became of.",
      f5: "Tonight there is a key on a doorstep",
      f6: "and a folded sheet of paper under it.",
      f7: "You can pick it up or leave it where it is.",
      f8: "Nobody is ever going to ask you why you picked it up.",
      pulsa: "Tap to continue",
    },
  },
};

/** The whole table for one locale. Unknown locales fall back to Spanish, the source language. */
export function getCopy(locale = "es") {
  return COPY[locale] ?? COPY.es;
}

export const LOCALES = Object.keys(COPY);

export default COPY;
