export const UI_COPY = {
  es: {
    title: "Golf Tour 2D Pro",
    subtitle: "Mini golf side-view con 400 niveles, biomas variados, obstaculos dinamicos y campos extendidos por zonas.",
    modeTags: {
      menu: "Campana Arcade",
      playing: "En juego",
      paused: "Pausa tactica",
      levelComplete: "Nivel completado",
      campaignComplete: "Tour completado",
    },
    labels: {
      play: "Jugar",
      continue: "Continuar",
      restart: "Reiniciar",
      next: "Siguiente nivel",
      retry: "Reintentar",
      levelSelect: "Seleccion de nivel",
      backMenu: "Menu",
      pause: "Pausa",
      resume: "Reanudar",
      fullscreen: "Pantalla completa",
      world: "Entorno",
      level: "Nivel",
      par: "Par",
      strokes: "Golpes",
      totalStrokes: "Golpes Tour",
      stars: "Estrellas",
      time: "Tiempo",
      best: "Mejor",
      difficulty: "Dificultad",
      objective: "Objetivo",
      controls: "Controles",
      status: "Estado",
      quality: "Calidad de tiro",
      launch: "Lanzar",
      qualityLocked: "Tiro bloqueado",
      physics: "Fisica",
      wind: "Viento",
      surface: "Superficie",
      hazards: "Riesgos",
      campaign: "Campana",
      zone: "Zona",
      angleDown: "Angulo -",
      angleUp: "Angulo +",
      powerDown: "Potencia -",
      powerUp: "Potencia +",
    },
    controlsDesktop:
      "Raton: arrastra desde la bola para apuntar y definir potencia. Teclado: A/D o flechas (angulo), W/S o flechas (potencia), Espacio/Enter lanza, P pausa, R reinicia, L selector, F pantalla completa.",
    controlsTouch:
      "Movil/tablet: arrastra siempre con el dedo sobre el escenario para definir angulo y potencia de la trayectoria completa de la bola; al soltar, golpeas. Los botones tactiles quedan como apoyo opcional.",
    objective:
      "Emboca con el menor numero de golpes posible. Cada nivel combina superficies, hazards, bumpers, zonas de viento y muros en distintos biomas de dia y noche.",
    status: {
      ready: "Listo para tirar.",
      moving: "Bola en movimiento.",
      paused: "Simulacion pausada.",
      sunk: "Bola embocada.",
      hazard: "Hazard detectado. Bola repuesta con penalizacion.",
      out: "Fuera de limites. Bola repuesta con penalizacion.",
      checkpoint: "Checkpoint cruzado. Avanzas a la siguiente zona del campo.",
    },
    quality: {
      perfect: "Perfecto",
      clean: "Limpio",
      standard: "Estandar",
      recovery: "Recuperacion",
    },
    overlays: {
      menuDescription:
        "Campana profesional con 400 trazados laterales y campos extendidos por zonas. Cada mapa usa siluetas de suelo con capas visuales, pendientes, hoyo tipo tubo y bandera como en mini golf clasico.",
      continueHint: "Continua desde el ultimo nivel desbloqueado o abre la seleccion completa.",
      pausedHint: "Ajusta angulo y potencia antes de relanzar.",
      completeHint: "El control de golpes y la gestion de obstaculos determinan estrellas y calidad.",
      campaignHint: "Tour completo. Puedes repetir niveles para optimizar estrellas y golpes.",
    },
    metrics: {
      coordinates: "Origen arriba-izquierda | X derecha | Y abajo",
      friction: "Friccion",
      bounce: "Rebote",
      speed: "Velocidad",
      windForce: "Fuerza viento",
    },
    difficulty: {
      rookie: "Rookie",
      pro: "Pro",
      elite: "Elite",
      master: "Master",
    },
  },
  en: {
    title: "Golf Tour 2D Pro",
    subtitle: "Side-view mini golf with 400 levels, diverse biomes, dynamic obstacles, and multi-zone extended courses.",
    modeTags: {
      menu: "Arcade Campaign",
      playing: "Live",
      paused: "Tactical Pause",
      levelComplete: "Level Cleared",
      campaignComplete: "Tour Cleared",
    },
    labels: {
      play: "Play",
      continue: "Continue",
      restart: "Restart",
      next: "Next level",
      retry: "Retry",
      levelSelect: "Level select",
      backMenu: "Menu",
      pause: "Pause",
      resume: "Resume",
      fullscreen: "Fullscreen",
      world: "Biome",
      level: "Level",
      par: "Par",
      strokes: "Strokes",
      totalStrokes: "Tour strokes",
      stars: "Stars",
      time: "Time",
      best: "Best",
      difficulty: "Difficulty",
      objective: "Objective",
      controls: "Controls",
      status: "Status",
      quality: "Shot quality",
      launch: "Launch",
      qualityLocked: "Shot locked",
      physics: "Physics",
      wind: "Wind",
      surface: "Surface",
      hazards: "Hazards",
      campaign: "Campaign",
      zone: "Zone",
      angleDown: "Angle -",
      angleUp: "Angle +",
      powerDown: "Power -",
      powerUp: "Power +",
    },
    controlsDesktop:
      "Mouse: drag from the ball to aim and set power. Keyboard: A/D or arrows (angle), W/S or arrows (power), Space/Enter shoot, P pause, R restart, L level select, F fullscreen.",
    controlsTouch:
      "Mobile/tablet: always drag your finger on the stage to set the ball's full trajectory angle and power, then release to shoot. On-screen buttons remain as optional backup controls.",
    objective:
      "Sink the ball in as few strokes as possible. Levels mix surface patches, hazards, bumpers, wind zones, and walls across day/night biomes.",
    status: {
      ready: "Ready to launch.",
      moving: "Ball in motion.",
      paused: "Simulation paused.",
      sunk: "Ball sunk.",
      hazard: "Hazard detected. Ball reset with penalty.",
      out: "Out of bounds. Ball reset with penalty.",
      checkpoint: "Checkpoint crossed. Advancing to the next field zone.",
    },
    quality: {
      perfect: "Perfect",
      clean: "Clean",
      standard: "Standard",
      recovery: "Recovery",
    },
    overlays: {
      menuDescription:
        "Professional campaign with 400 lateral layouts and multi-zone extended courses. Every map uses layered ground silhouettes, slope geometry, and a tube-style cup + flag target inspired by classic mini golf scenes.",
      continueHint: "Continue from the latest unlocked level or open full level select.",
      pausedHint: "Tune angle and power before relaunching.",
      completeHint: "Stroke control and obstacle handling determine stars and execution quality.",
      campaignHint: "Tour completed. Replay levels to optimize stars and stroke count.",
    },
    metrics: {
      coordinates: "Origin top-left | X right | Y down",
      friction: "Friction",
      bounce: "Bounce",
      speed: "Speed",
      windForce: "Wind force",
    },
    difficulty: {
      rookie: "Rookie",
      pro: "Pro",
      elite: "Elite",
      master: "Master",
    },
  },
};

export function localize(copy, locale) {
  return copy[locale] ?? copy.en;
}
